ALTER TABLE `city` CHANGE `galaxy` `x` INT(15) UNSIGNED NOT NULL DEFAULT '0', CHANGE `system` `y` INT(15) UNSIGNED NOT NULL DEFAULT '0', CHANGE `pos` `z` INT(15) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `city_build_que` DROP FOREIGN KEY `city_build_que_ibfk_1`;
ALTER TABLE `city_resources` DROP FOREIGN KEY `city_resources_ibfk_1`;
ALTER TABLE `resmov` DROP FOREIGN KEY `resmov_ibfk_1`;
ALTER TABLE `city_builds` DROP FOREIGN KEY `city_builds_ibfk_1`;
ALTER TABLE `units` DROP FOREIGN KEY `units_ibfk_3`; ALTER TABLE `units` DROP FOREIGN KEY `units_ibfk_4`; ALTER TABLE `units` DROP FOREIGN KEY `units_ibfk_5`;
ALTER TABLE `unit_que` DROP FOREIGN KEY `unit_que_ibfk_2`;

ALTER TABLE `city` CHANGE `id` `id` INT(15) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `city_builds` ADD FOREIGN KEY (`city`) REFERENCES `city`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `city_build_que` ADD FOREIGN KEY (`city`) REFERENCES `city`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `city_resources` ADD FOREIGN KEY (`city_id`) REFERENCES `city`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `resmov` ADD FOREIGN KEY (`to`) REFERENCES `city`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `units` ADD FOREIGN KEY (`from`) REFERENCES `city`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT; ALTER TABLE `units` ADD FOREIGN KEY (`to`) REFERENCES `city`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `units` ADD FOREIGN KEY (`where`) REFERENCES `city`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `unit_que` ADD FOREIGN KEY (`city`) REFERENCES `city`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;


UPDATE `conf` SET `sge_ver` = '121' WHERE `sge_ver` = '120';
ALTER TABLE `city` ADD UNIQUE( `x`, `y`, `z`);