<?php

//general

$l_yes 			 = "Si";
$l_no			 = "No";
$l_here			 = "aqui";
$l_submit		 = "Enviar";
$l_reset		 = "Borrar";
$l_all			 = "Todo";

$l_ore			 = "Oro";
$l_commodities		 = "Articulos";
$l_organics		 = "Minerales";
$l_goods		 = "Bienes";
$l_energy		 = "Energia";
$l_colonists		 = "Colonos";
$l_credits 		 = "Creditos";
$l_units		 = "unidades de ";
$l_special		 = "Especial";

$l_cargo		 = "Cargo";
$l_fighters		 = "Cazas ";
$l_mines		 = "Minas ";
$l_torps		 = "Torpedos";

$l_none			 = "Ninguno";
$l_unnamed		 = "Sin nombre";
$l_name			 = "Nombre";
$l_unowned		 = "Sin propietario";
$l_unknown		 = "Desconocido";
$l_clickme 		 = "Pulsa aquí";
$l_player  		 = "Jugador";
$l_ship			 = "Nave";
$l_ships		 = "Naves";
$l_set			 = "set";
$l_realspace		 = "Espacio Real";
$l_armourpts		 = "Puntos de armadura";
$l_links		 = "Enlaces";

// main.php

$l_main_title 		 = "Menú principal";
$l_main_warpto = "Warp to";
$l_main_other = "Otro";

$l_traderoutes		 = "Rutas comerciales";
$l_trade_control	 = "Control de comercio";

$l_youhave 		 = "Tienes ";
$l_turns_used		 = "Turnos usados: ";
$l_turns_have		 = "Turnos disponibles: ";
$l_score		 = "Puntuacion: ";
$l_sector		 = "Sector";
$l_help			 = "Ayuda";
$l_faq		         = "Preguntas Frecuentes (FAQ)";
$l_feedback		 = "Comentarios";
$l_forums		 = "Foros";
$l_logout		 = "Salir";

$l_commands		 = "Comandos";
$l_command_no		 = "Comando no disponible.";
$l_devices		 = "Dispositivos";
$l_planets		 = "Planetas";
$l_log			 = "Log";
$l_sector_def		 = "Defensas del Sector";
$l_defense		 = "Defensas";
$l_read_msg		 = "Leer Mensajes";
$l_send_msg		 = "Enviar Mensajes";
$l_rankings		 = "Rankings";
$l_teams		 = "Alianzas";
$l_ohno			 = "Auto-Destruccion";
$l_options		 = "Opciones";
$l_navcomp		 = "Ordenador de Navegacion";

$l_incompletemove 	 = "No has completado tu movimiento anterior.";
$l_clicktocontinue	 = "Pulsa Aqui para continuar";
$l_toplanetmenu   	 = "para ir al menu del planeta.";
$l_nonexistant_pl	 = "En un planeta inexistente???";
$l_abord		 = ", a bordo de ";
$l_messages_wait	 = " Mensajes esperandote.";

$l_no_warplink		 = "Sin enlaces warp";
$l_scan			 = "escanear";
$l_fullscan		 = "Escaneo Completo";

$l_port			 = "Puerto";
$l_tradingport		 = "Puerto comercial";
$l_planet_in_sec	 = "Planetas en el sector ";
$l_ships_in_sec		 = "Otras naves en el sector ";
$l_sector_0		 = "Hay tanto trafico en el Sistema Solar (Sector 0) que no puedes ni siquiera puedes aislar otras naves!";

// report.php

$l_report_title		 = "Informe de la Nave";

$l_level		 = "Nivel";

$l_ship_levels		 = "Ship Component Levels";
$l_hull			 = "Casco";
$l_engines		 = "Motores";
$l_power		 = "Energía";
$l_computer		 = "Ordenador";
$l_sensors		 = "Sensores";
$l_armour		 = "Armadura";
$l_shields		 = "Escudos";
$l_beams		 = "Armas de Rayos";
$l_torp_launch	         = "Lanzadores de Torpedos";
$l_cloak		 = "Camuflaje";
$l_holds		 = "Bahias de carga";
$l_deflect		 = "Deflectores de Minas";
$l_ewd			 = "Dispositivo de Emergencia Warp";
$l_shipavg		 = "Nivel Tecnológico medio";

$l_arm_weap		 = "Armadura & Armas";
$l_beacons		 = "Faros Espaciales";
$l_warpedit		 = "Editores Warp";
$l_genesis		 = "Torpedos Genesis";
$l_escape_pod		 = "Modulo de Escape";
$l_fuel_scoop		 = "Generador de Fuel";

// device.php

$l_device_title		 = "Dispositivos";

$l_device_expl		 = "Tu nave está equipada con los siguientes dispositivos (pulsa en un dispositivo para usarlo):";
$l_device		 = "Dispositivo";
$l_qty			 = "Cantidad";
$l_usage		 = "Utilización";
$l_manual		 = "Manual";	
$l_automatic		 = "Automatico";

// port.php port2.php
// port.php port2.php
$l_trade		 = "Comerciar"; 
$l_title_port		 = "Comerciar con Puerto"; 
$l_title_trade		 = "Comerciar Mercancías"; 
$l_sector_war		 = "Embargo de Guerra"; 
$l_war_info		 = "La guerra está azotando este sector. No puedes llegar al puerto a través de todas las fuerzas hostiles."; 
$l_no_trade		 = "Comercio prohibido"; 
$l_no_trade_out		 = "El comercio en este puerte no está permitido a los extranjeros"; 
$l_no_trade_info	 = "El comercio en este puerto no está permitido"; 
$l_buying		 = "Comprando"; 
$l_selling		 = "Vendiendo"; 
$l_commodity		 = "Mercancía"; 
$l_amount		 = "Cantidad"; 
$l_price		 = "Precio"; 
$l_buy			 = "Comprar"; 
$l_sell			 = "Vender"; 
$l_trade_st_info	 = "Tienes [free_holds] contenedores de carga vacíos. Puedes llevar [free_power] unidades de energía más. Tienes [credits] créditos."; 
$l_special_port		 = "Puerto Especial"; 
$l_no_credits		 = "Te faltan créditos"; 
$l_creds_to_spend	 = "Tienes [credits] créditos para gastar."; 
$l_cost			 = "Coste"; 
$l_avail		 = "Disponible"; 
$l_profit		 = "Beneficio"; 
$l_current		 = "Actual"; 
$l_current_qty		 = "Cantidades Actuales"; 
$l_max			 = "Max"; 
$l_ifyouneedmore	 = "Si necesitas más créditos puedes acceder al [igb] de este puerto "; 
$l_ifyouneedplan	 = "Acceder al "; 
$l_igb_term		 = "Terminal Bancario IGB"; 
$l_upgrade		 = "¿Actualizar?"; 
$l_unlimited		 = "ilimitado"; 
$l_full			 = "Lleno"; 
$l_equipped		 = "Equipado"; 
$l_n_a			 = "n/a"; 
$l_item			 = "Unidad"; 
$l_totalcost		 = "Coste Total"; 
$l_would_dump	         = "Si quieres puedes soltar a todos tus colonos aquí, pulsa "; 
$l_noport		 = "¡Aquí no hay ningún puerto!"; 
$l_trade_turnneed	 = "Necesitas al menos un turno para comerciar con un puerto o planeta."; 
$l_returnto_port         = "Pulsa <A HREF=port.php>aquí</A> para volver al menú del puerto."; 
$l_notenough_cargo	 = "No tienes suficientes contenedores vacíos para las mercancías que quieres comprar."; 
$l_notenough_power	 = "No tienes suficiente espacio libre de energía para la energía que quieres conseguir."; 
$l_notenough_credits	 = "No tienes suficientes créditos para completar la transacción."; 
$l_notenough_turns	 = "No tienes suficientes turnos para completar la transacción."; 
$l_notenough_ore	 = "No tienes suficientes minerales para completar la transacción."; 
$l_notenough_goods	 = "No tienes suficientes bienes para completar la transacción."; 
$l_notenough_energy	 = "No tienes suficiente energía para completar la transacción."; 
$l_notenough_organics	 = "No tienes suficientes orgánicos para completar la transacción."; 
$l_exceed_organics	 = "El número de orgánicos supera la oferta/demanda.  "; 
$l_exceed_ore            = "El número de minerales supera la oferta/demanda.  "; 
$l_exceed_energy         = "El número de energía supera la oferta/demanda.  "; 
$l_exceed_goods          = "El número de bienes supera la oferta/demanda.  "; 
$l_trade_result		 = "Resultado de esta transacción"; 
$l_traded_ore		 = "Minerales comerciados"; 
$l_traded_goods		 = "Bienes comerciados"; 
$l_traded_organics	 = "Orgánicos comerciados"; 
$l_traded_energy	 = "Energía comerciados"; 
$l_trade_complete	 = "Transacción completada"; 
$l_trade_upgraded = "Actualizado al nivel "; 
$l_trade_added = "añadido"; 
$l_trade_installed = "instalado"; 


/*
$l_trade		 = "Comercio";
$l_title_port		 = "Puerto Comercial";
$l_title_trade		 = "Comercio de Artículos";
$l_sector_war		 = "Embargo por guerra";
$l_war_info		 = "La guerra asola este sector. No puedes alcanzar el puerto debido a las fuerzas hostiles.";
$l_no_trade		 = "Comercio Prohibido";
$l_no_trade_out		 = "Trading at this port is not allowed for outsiders";
$l_no_trade_info	 = "Trading at this port is not allowed";
$l_buying		 = "Buying";
$l_selling		 = "Selling";
$l_commodity		 = "Commodity";
$l_amount		 = "Amount";
$l_price		 = "Price";
$l_buy			 = "Buy";
$l_sell			 = "Sell";
$l_trade_st_info	 = "You have [free_holds] empty cargo holds, can carry [free_power] more energy units, and have [credits] credits.";
$l_special_port		 = "Special Port";
$l_no_credits		 = "Not enough credits";
$l_creds_to_spend	 = "You have [credits] credits to spend.";
$l_cost			 = "Cost";
$l_avail		 = "Available";
$l_profit		 = "Profit";
$l_current		 = "Current";
$l_current_qty		 = "Current Quantities";
$l_max			 = "Max";
$l_ifyouneedmore	 = "If you need more you may access this port's [igb] ";
$l_ifyouneedplan	 = "Access the planet's";
$l_igb_term		 = "IGB Banking Terminal";
$l_upgrade		 = "Upgrade?";
$l_unlimited		 = "Unlimited";
$l_full			 = "Full";
$l_equipped		 = "Equipped";
$l_n_a			 = "n/a";
$l_item			 = "Item";
$l_totalcost		 = "Total cost";
$l_would_dump	         = "If you would like to dump all your colonists here, click ";
$l_noport		 = "There is no port here!";
$l_trade_turnneed	 = "You need at least one turn to trade at a port or planet.";
$l_returnto_port         = " Click <A HREF=port.php>here</A> to return to the port menu.";
$l_notenough_cargo	 = "You do not have enough free cargo holds for the commodities you wish to purchase.";
$l_notenough_power	 = "You do not have enough free power storage for the energy you wish to purchase.";
$l_notenough_credits	 = "You do not have enough credits to complete the transaction.";
$l_notenough_turns	 = "You do not have enough turns to complete the transaction.";
$l_notenough_ore	 = "You do not have enough ore to complete the transaction.";
$l_notenough_goods	 = "You do not have enough goods to complete the transaction.";
$l_notenough_energy	 = "You do not have enough energy to complete the transaction.";
$l_notenough_organics	 = "You do not have enough organics to complete the transaction.";
$l_exceed_organics	 = "Number of organics exceeds the supply/demand.  ";
$l_exceed_ore            = "Number of ore exceeds the supply/demand.  ";
$l_exceed_energy         = "Number of energy exceeds the supply/demand.  ";
$l_exceed_goods          = "Number of goods exceeds the supply/demand.  ";
$l_trade_result		 = "Results for this trade";
$l_traded_ore		 = "Traded Ore";
$l_traded_goods		 = "Traded Goods";
$l_traded_organics	 = "Traded Organics";
$l_traded_energy	 = "Traded Energy";
$l_trade_complete	 = "Trade completed";
$l_trade_upgraded = "Upgraded to level ";
$l_trade_added = "added";
$l_trade_installed = "installed";
*/



/*
// planet.php planet2.php planet3.php
$l_planet_title		 = "Planet Menu";
$l_planet_none		 = "You are not in the same sector as this planet, so you can't interact with it.";
$l_planet_capture1	 = "capture"; // thats the link's text
$l_planet_capture2	 = "You may [capture] the planet or just leave it undefended.";
$l_planet_unowned	 = "This planet is unowned";
$l_planet_unnamed        = "Welcome to [name]'s un-named planet.";
$l_planet_named		 = "Welcome to [planetname], owned by [name].";
$l_planet_onsurface	 = "You are presently on the surface of the planet.";
$l_planet_orbit 	 = "You are presently in orbit of the planet.";
$l_planet_leave_link     = "Leave";
$l_planet_leave          = "[leave] Planet";
$l_planet_name_link = "Name";
$l_planet_name2 = "[name] planet";
$l_planet_land_link      = "Land";
$l_planet_land           = "[land] on Planet";
$l_planet_logout	 = "You can also <a href=logout.php>log-out</a> in the safety of your planet.";
$l_planet_selling	 = "Planet is presently selling commodities.";
$l_planet_not_selling    = "Planet is not presently selling commodities.";
$l_planet_transfer_link	 = "Transfer";
$l_planet_transfer	 = "[transfer] commodities/resources/colonists to/from Planet";
$l_planet_hasbase	 = "You have a base on this planet.";

$l_planet_perc		 = "Production Percentages";
$l_planet_interest	 = "* Production of credits beyond banking interest is 100 - other percentages";
$l_planet_update	 = "Update";
$l_planet_tsell_link	 = "Selling";
$l_planet_tsell		 = "Toggle planet [selling] commodities";
$l_planet_bbase_link	 = "build a base";
$l_planet_bbase		 = "With enough commodites and credits, you can [build] to help defend the planet.";
$l_planet_bbuild	 = "Base constructed";
$l_planet_mcorp_linkC	 = "Corporate Planet";
$l_planet_mcorp_linkP	 = "Personal Planet";
$l_planet_mcorp		 = "You can also make this planet a [planet].";
$l_planet_buy_link	 = "Buy";
$l_planet_buy		 = "[buy] commodities from Planet";
$l_planet_att_link	 = "Attack";
$l_planet_att		 = "[attack] on Planet";
$l_planet_att_sure	 = "Are you SURE...";
$l_planet_scn_link	 = "Scan";
$l_planet_scn		 = "[scan] Planet";
$l_planet_nowsell        = "Planet now set to sell.";
$l_planet_nownosell      = "Planet now set not to sell.";
$l_planet_iname		 = "Enter new planet name";
$l_planet_cname		 = "Planet name changed to ";
$l_planet_landed	 = "You have landed on the planet's surface.";
$l_planet_left		 = "You are no longer on the planet's surface.";
$l_planet_cinfo		 = "You have room for [cargo] units of additional cargo.  You have capacity for [energy] units of addtional power.";
$l_planet_toplanet	 = "To Planet?";
$l_planet_baseinfo	 = "To build a base there must be at least $base_credits credits, $base_ore units of ore, $base_organics units of organics, and $base_goods units of goods on the planet .";
$l_planet_p_under        = "You may not change production percentages to a negative number.";
$l_planet_p_over	 = "You may not change production percentages to higher than a total of 100%.";
$l_planet_p_changed	 = "Production percentages changed.";
$l_plant_scn_turn	 = "You need at least one turn to scan a planet.";
$l_planet_noscan	 = "Sensors cannot get a fix on target!";
$l_planet_logscanA	 = "[name] attempted to scan one of your planets in sector [sector], but failed.";
$l_planet_logscanB	 = "One of your planets in sector [sector] was scanned by [name].";
$l_planet_scn_report	 = "Scan results on [name], owned by:  [owner]";
$l_base	  		 = "Base";
$l_planet_ison		 = "is on the planet.";
$l_planet_captured	 = "Planet captured";
$l_planet_notdef	 = "Planet not defeated!";
$l_planet_caplog	 = "Your planet '[planetname]' in sector [sector] was captured by [name].";
$l_planet_noone = "nobody";

$l_planet2_title	 = "Planetary Transfer";
$l_planet2_noturn	 = "You need at least one turn to perform a planetary transfer.";
$l_planet2_noten 	 = "You don't have enough ";
$l_planet2_fortr	 = "for the requested transfer.";
$l_planet2_settr	 = "Setting transfer amount to ";
$l_planet2_losup	 = "The planet was only able to supply ";
$l_planet2_notowner	 = "You do not own this planet.";
$l_planet2_compl	 = "Transfer complete.";
$l_planet2_power	 = "power capacity";
$l_planet2_comp 	 = "computer capacity";
$l_planet2_laun 	 = "launcher capacity";
$l_planet2_nocorptransfer = "You cannot transfer credits to or from corporate planets.";
$l_planet2_baseexceeded = "Planets without a base can not hold that amount of credits.";

$l_planet3_title	 = "Trading at Planet";

// planet-report.php

$l_pr_title		 = "Planet Report";
$l_pr_teamlink		 = "Show alliance planets";
$l_pr_noplanet		 = "You have no planets so far";
$l_pr_clicktosort	 = "Click on column header to sort.";
$l_pr_totals		 = "Totals";

// rsmove.php
$l_rs_title 		= "RealSpace Move";
$l_rs_whichsector       = "Which sector would you like to reach through RealSpace?";
$l_rs_insector		= "You are presently in sector [sector] - and there are sectors available from 0 to [sector_max].";
$l_rs_submit		= "Compute";
$l_rs_movetime		= "With your engines, it will take [triptime] turns to complete the journey.";
$l_rs_energy		= "You would gather [energy] units of energy";
$l_rs_noturns		= "You do not have enough turns left, and cannot embark on this journey.";
$l_rs_engage_link	= "Engage";
$l_rs_engage		= "You have [turns] turns. [engage] engines?";

$l_rs_invalid		= "Invalid Destination";
$l_rs_ready 		= "You are now in sector [sector]. You used [triptime] turns, and gained [energy] energy units.";

// navcomp.php	

$l_nav_title		 = "Navigation Computer";
$l_nav_nocomp		 = "Navigation computer is not available";
$l_nav_query		 = "Enter sector to find path to: ";
$l_nav_pathfnd		 = "Path found";
$l_nav_answ1		 = "It will take you";
$l_nav_answ2		 = "turns to get to this sector.";
$l_nav_proper		 = "Your computer technology is too primitive to compute a warp route to that distance.";


// attack.php

$l_att_title		 = "Attack Ship";
$l_att_notarg		 = "Target not in this sector.";
$l_att_noturn		 = "You need at least one turn to attack.";
$l_att_noatt		 = "Attacking someone in this sector is not permitted.";
$l_att_flee		 = "Target out maneuvered you!";
$l_att_ewd		 = "Target engaged an emergency warp device when attacked!";
$l_att_att		 = "Attacking ";
$l_att_beams		 = "Beams hit:";
$l_att_torps		 = "Torpedos hit:";
$l_att_fighters		 = "Fighters Attack:";
$l_att_lost		 = "lost";
$l_att_ylost		 = "You lost";
$l_att_sdown		 = "'s shields are down!";
$l_att_ydown		 = "Your shields are down!";
$l_att_shits		 = "'s shields are hit for";
$l_att_yhits		 = "Your shields are hit for";
$l_att_dmg		 = "damage";
$l_att_sarm		 = "'s armour breached!";
$l_att_yarm		 = "Your armour has been breached!";
$l_att_ashit		 = "'s armour is hit for";
$l_att_ayhit		 = "Your armour is hit for";
$l_att_lostf		 = "lost all fighters.";
$l_att_ylostf		 = "You lost all fighters.";
$l_att_sdest		 = "'s ship has been destroyed.";
$l_att_espod		 = "An escape pod was launched!";
$l_att_ysalv		 = "You salvaged [salv_ore] units of ore, [salv_organics] units of organics, [salv_goods] units of goods, and salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits.<BR>Your rating changed by [rating_change] points.";
$l_att_andused		 = "and used";
$l_att_stilship		 = "You did not destory [name]'s ship.";
$l_att_atyou		 = "attacked you";
$l_att_and		 = "and";
$l_att_yshiplost	 = "Your ship has been destroyed!";
$l_att_salv		 = "[name] salvaged [salv_ore] units of ore, [salv_organics] units of organics, [salv_goods] units of goods, and salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits";

// warpedit 1-3.php

$l_warp_title		 = "Use Warp Editor";
$l_warp_turn		 = "You need at least one turn to use a warp editor.";
$l_warp_none		 = "You do not have any warp editors.";
$l_warp_forbid		 = "Using a Warp Editor in this sector is not permitted.";
$l_warp_nolink		 = "There are no links out of this sector.";
$l_warp_linkto		 = "Links lead from this sector to";
$l_warp_query		 = "What sector would you like to create a link to?";
$l_warp_oneway		 = "One-way?";
$l_warp_dest		 = "Alternately, you may destroy a link to sector.";
$l_warp_destquery	 = "What sector would you like to remove a link to?";
$l_warp_bothway		 = "Both-ways";
$l_warp_nosector	 = "Sector does not exist.";
$l_warp_twoerror	 = "Using a Warp Editor to create a two-way link to sector [target_sector] is not permitted.";
$l_warp_sectex		 = "Cannot create warp link from current sector - that would exceed the maximum of $link_max per sector.";
$l_warp_linked		 = "Target sector ([target_sector]) already has a link from this sector.";
$l_warp_unlinked	 = "Target sector ([target_sector]) does not have a link from this sector.";
$l_warp_coneway	         = "Link created one-way to";
$l_warp_ctwoway		 = "Link created to and from";
$l_warp_forbidtwo	 = "Using a Warp Editor to remove a two-way link to sector [target_sector] is not permitted.";
$l_warp_removed		 = "Link removed to";
$l_warp_removedtwo	 = "Link removed to and from";

// genesis.php

$l_gns_title		 = "Use Genesis Device";
$l_gns_turn		 = "You need at least one turn to use a genesis device.";
$l_gns_onplanet		 = "You can't use this device while on the planet surface.";
$l_gns_full		 = "This solar system is already full.";
$l_gns_planetex		 = "There is already a planet in this sector.";
$l_gns_nogenesis	 = "You do not have any genesis devices.";
$l_gns_forbid		 = "Creating a planet in this sector is not permitted.";
$l_gns_bforbid		 = "The bases in this sector are interfering with your genesis device. Planet creation not possible.";
$l_gns_pcreate		 = "Planet created.";

// ship.php

$l_ship_title		 = "Ship Commands";
$l_ship_the		 = "The";
$l_ship_nolonger	 = "is no longer in sector";
$l_ship_youc		 = "You see the";
$l_ship_owned		 = "owned by";
$l_ship_perform		 = "You can perform the following actions:";

// selfdestruct.php

$l_die_title		 = "Self-Destruct";
$l_die_rusure		 = "Are you sure you wish to destroy your ship? This will remove you from the game.";
$l_die_goodbye		 = "Goodbye cruel galaxy!";
$l_die_check		 = "Are you positive that you wish to remove yourself from the game?";
$l_die_nonono		 = "NO! NO! NO!";
$l_die_what		 = "What was I thinking?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor		 = "You ship and all aboard have been vaporized.";
$l_die_please		 = "Please, <A HREF=logout.php>logout</A>";
$l_die_exploit		 = "Don't play with what you don't understand.";

// move.php

$l_move_title 		 = "Move";
$l_move_turn		 = "You need at least one turn to move.";
$l_move_failed		 = "Move failed!";

// scan.php

$l_scan_title		 = "Scan Ship";
$l_scan_turn		 = "You need at least one turn to scan another ship.";
$l_scan_ron		 = "Scan results on";
$l_scan_capt		 = "Captained by:";
$l_scan_arma		 = "Armament:";
$l_scan_carry		 = "Carrying:";

// lrscan.php

$l_lrs_title		 = "Long Range Scan";
$l_lrs_nofull		 = "Your scanners do not possess full long range scan capabilities.";
$l_lrs_noturns		 = "You need at least $fullscan_cost turn(s) to run a full long range scan.";
$l_lrs_used		 = "Used";
$l_lrs_turns		 = "turn(s)";
$l_lrs_left		 = "left";
$l_lrs_reach		 = "The following locations can be reached from sector [sector]:";
$l_lrs_links		 = "Links";
$l_lrs_ships		 = "Ships";
$l_lrs_click		 = "Click one of the links to move to that sector.";
$l_lrs_cantscan		 = "Can't scan sector from current sector!";
$l_lrs_zero		 = "Sector 0 is too crowded to scan for ships!";
$l_lrs_moveto		 = "to move to sector";
$l_log_titlet = "View Log";

// log.php

$l_log_months = array('January','February','March','April','May','June','July','August','September','October','November','December');
$l_log_months_short = array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
$l_log_pod = "Luckily, you had an escape pod!";
$l_log_nopod = "<font color=yellow><b>You did not have an escape pod, you died.</b></font>";
$l_log_log = "[player]'s Log";
$l_log_start = "Log entry for";
$l_log_end = "End of log entry for";
$l_log_click = "Click <A HREF=main.php><font color=#00ff00>here</font></A> to return to the main menu.";
$l_log_note = "NOTE: If this page displays incorrectly, or if you simply don't like the dynamic html effects or find them annoying, you can disable them <a href=options.php><font color=#00FF00>here</font>";

$l_log_text[LOG_LOGIN] = "You have logged in, from [ip].";
$l_log_title[LOG_LOGIN] = "Logged in";
$l_log_text[LOG_LOGOUT] = "You have logged out, from [ip].";
$l_log_title[LOG_LOGOUT] = "Logged out";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] was spotted on an attack vector, but your great pilot skills and good engines allowed you to outmaneuver the enemy.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Evasive action!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "You detected [player]'s weapons trying to fix on your ship, but your cloak generators managed to fool the enemy's primitive sensor circuits.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Cloak successful!";
$l_log_text[LOG_ATTACK_EWD] = "You are surprised by [player]'s treacherous attack. You can see the incoming warheads as you reach frantically for the emergency warp button. The world blurs around you and, for a milisecond, you think you are dead. When you finally open your eyes, you see that you were safely transported elsewhere. But where exactly, you do not know...";
$l_log_title[LOG_ATTACK_EWD] = "Emergency warp!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Your sensors detect [player]'s ship on an attack vector. \"Better be safe than sorry\", you think, hitting the emergency warp button. You hear a strange choking sound coming from the engines room and smell burned circuitry. \"Stupid piece of crap!\", you yell, kicking at the computer. The computer emits beeps of protestation as you prepare for the incoming battle...";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Emergency warp <font color=red>failed!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "You ship is being attacked by [player]. Try as you might, you cannot defend yourself against [player]'s superior weaponry. Your ship was destroyed. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Combat lost!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "You ship was attacked by [player]. You battle for a while, then the fight breaks down. You lost [armor] armor points and [fighters] fighters in the skirmish.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Skirmish!</font>";
$l_log_text[LOG_TOLL_PAID] = "You had to pay [toll] credits to enter sector [sector]. You promise yourself that you'll find a way to get your money back.";
$l_log_title[LOG_TOLL_PAID] = "Extortion";
$l_log_text[LOG_HIT_MINES] = "You hit [mines] mines when travelling in sector [sector].";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Mines alert!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Your ship was destroyed by a minefield in sector [sector]. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Mines alert!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Your planet [planet_name] in sector [sector] was captured in battle by [name]. Fortunately, the strong loyalty of your citizens played in your favor. They have bravely chosen to destroy the planet rather than have it fall into enemy hands. You organize superb funerals in the memory of your faithful people.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planet destroyed</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Your planet [planet_name] in sector [sector] was captured in battle by the wretched [name]. The people of the planet welcome their new ruler. You hear a testimony on BNN : \"We're glad to be rid of that old fart! We don't want no stinking loser who can't protect us!\". You swear to make them pay for their arrogance.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planet captured!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Your planet [planet_name] in sector [sector] was attacked by [name]. The citizens organized a valliant defense however, and managed to destroy the opponent. They salvage some resources from the space debris : [goods] goods, [ore] ore, [organics] organics and [salvage]% of the ship's worth of [credits] credits.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Victory!";
$l_log_title[LOG_RAW] = "Notice";
$l_log_text[LOG_TOLL_RECV] = "Your fighters in sector [sector] have collected a 'tax' of [toll] credits.";
$l_log_title[LOG_TOLL_RECV] = "Toll income";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] were destroyed in sector [sector].";
$l_log_title[LOG_DEFS_DESTROYED] = "Sector defenses destroyed";
$l_log_text[LOG_PLANET_EJECT] = "You have been ejected from the planet in sector [sector] because [name] left the alliance.";
$l_log_title[LOG_PLANET_EJECT] = "Ejected!";
$l_log_text[LOG_BADLOGIN] = "There has been a bad login attempt from [ip].";
$l_log_title[LOG_BADLOGIN] = "Bad login";
$l_log_text[LOG_PLANET_SCAN] = "[name] has scanned your planet [planet_name] in sector [sector].";
$l_log_title[LOG_PLANET_SCAN] = "Planet scan";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] has attempted to scan your planet [planet_name] in sector [sector], but failed.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Planet scan failed";
$l_log_text[LOG_SHIP_SCAN] = "[player] has scanned your ship.";
$l_log_title[LOG_SHIP_SCAN] = "Ship scan";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] has attempted to scan your ship, but failed.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Ship scan failed";
$l_log_text[LOG_Xenobe_ATTACK] = "Attacking [player]...";
$l_log_title[LOG_Xenobe_ATTACK] = "Attack";
$l_log_text[LOG_STARVATION] = "One of your planet in [sector] cannot sustain its population! More organics is needed. [starvation] colonists died of hunger.";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Starvation!</font>";
$l_log_title[LOG_TOW] = "Towed!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "You have destroyed [fighters] patrolling fighters in sector [sector].";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Fighters destroyed";
$l_log_text[LOG_DEFS_KABOOM] = "You were destroyed by a fighters force in sector [sector]. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Ship destroyed!</font>";
$l_log_text[LOG_HARAKIRI] = "You were tired of captaining this space barge, so you decided the universe would be better without it. Authorized by [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Self-destructed!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] has rejected an invitation to join your alliance, [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Invitation rejected";
$l_log_text[LOG_TEAM_RENAME] = "You have renamed your alliance to [team].";
$l_log_title[LOG_TEAM_RENAME] = "Alliance renamed";
$l_log_text[LOG_TEAM_M_RENAME] = "Your alliance coordinator renamed the alliance to [team].";
$l_log_title[LOG_TEAM_M_RENAME] = "Alliance renamed";
$l_log_text[LOG_TEAM_KICK] = "You have been ejected from the alliance [team].";
$l_log_title[LOG_TEAM_KICK] = "Ejected from alliance!";
$l_log_text[LOG_TEAM_CREATE] = "You have created a new alliance, [team].";
$l_log_title[LOG_TEAM_CREATE] = "Created new alliance";
$l_log_text[LOG_TEAM_LEAVE] = "You have left alliance [team].";
$l_log_title[LOG_TEAM_LEAVE] = "Left alliance";
$l_log_text[LOG_TEAM_NEWLEAD] = "You have left the alliance [team]. You relinquished the alliance leadership to [name].";
$l_log_title[LOG_TEAM_NEWLEAD] = "Left alliance";
$l_log_text[LOG_TEAM_LEAD] = "Your alliance coordinator has decided to leave [team]. You have been appointed to take its place.";
$l_log_title[LOG_TEAM_LEAD] = "Promotion!";
$l_log_text[LOG_TEAM_JOIN] = "You have joined the alliance [team].";
$l_log_title[LOG_TEAM_JOIN] = "Joined alliance";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] has accepted to join [team]. This brings you one step further to galactic domination.";
$l_log_title[LOG_TEAM_NEWMEMBER] = "New alliance member";
$l_log_text[LOG_TEAM_INVITE] = "You have been invited to be part of [team].";
$l_log_title[LOG_TEAM_INVITE] = "Invitation";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] has left your alliance.";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Alliance loses a member";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] has self-destructed from ip [ip].";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Self-destruct";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] had [quantity] [type], with max holds of [holds]";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Illegal ship value";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] has attempted to capture [defender]'s planet in sector [sector]. Planet was destroyed instead.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planet destroyed";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Sector Defences Fighters in sector [sector] degraded by [degrade] percent due to insufficient energy.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "Sector Defences degraded.";
$l_log_text[LOG_PLANET_CAPTURED] = "You captured a planet belonging to [owner]. It had [cols] colonists and [credits] credits on it.";
$l_log_title[LOG_PLANET_CAPTURED] = "Planet captured!";

// modify-defences.php

$l_md_title		 = "Sector Defences";
$l_md_invalid		 = "Invalid Sector Defence";
$l_md_nolonger		 = "The sector defence selected is no longer there.";
$l_md_you		 = "you";
$l_md_bmines		 = "Your beams destroyed";
$l_md_msgdownerb	 = "[name] destroyed [mines] mines in sector [sector].";
$l_md_retr		 = "You retrieved";
$l_md_mode		 = "The fighters selected have been set to [mode] mode.";
$l_md_consist		 = "This sector defence consists of [qty] [type] owned by [owner].";
$l_md_youcan		 = "You can";
$l_md_retrieve		 = "Retrieve";
$l_md_change		 = "Change Fighter settings";
$l_md_cmode		 = "Fighter mode";
$l_md_attack		 = "Attack";
$l_md_toll		 = "Toll";
$l_md_attdef		 = "Attack the Sector Defences. All sector fighters will retaliate.";
$l_md_noturn	  	 = "You need at least one turn.";
$l_md_nothere            = "You need to be in the same sector as the sector defences.";
$l_md_notyours           = "Action not permitted. Those sector defences do not belong to you.";
$l_md_yours              = "You can not attack your own sector defences.";

// news.php

$l_news_title		 = "BlackNova Universe News";
$l_news_info		 = "BNN is among the galaxy's leaders<br>
                            in news and information delivery.<br>
                            Staffed 24 hours, seven days a week by a <br>
                            dedicated staff in BNN's galaxy headquarters <br>
                            in Alpha Centauri and in bureaus galaxywide!";
$l_news_for		 = "News for";
$l_news_prev		 = "previous day";
$l_news_next		 = "next day";
$l_news_none		 = "Sorry, no news today.";
$l_news_flash		 = "News Flash";

// dump.php

$l_dump_title		 = "Dumping colonists";
$l_dump_turn		 = "You need at least one turn to dump colonists.";
$l_dump_nocol		 = "You have no colonists on your ship to begin with.";
$l_dump_dumped		 = "Colonists dumped at supply depot.";
$l_dump_nono		 = "You need to be at a supply depot to do this.";

// readmail.php

$l_readm_title		 = "Read Message";

$l_readm_delete		 = "MESSAGE DELETED";
$l_readm_nomessage	 = "You have no Messages waiting for you...";
$l_readm_center		 = "Message Receiving Center";
$l_readm_sender		 = "Message Sender";
$l_readm_captn		 = "Captain of the";
$l_readm_del		 = "Delete";
$l_readm_repl		 = "Reply";

// mailto2.php

$l_sendm_title		 = "Send Message";
$l_sendm_to		 = "To";
$l_sendm_from		 = "From";
$l_sendm_ally		 = "Alliance:";
$l_sendm_subj		 = "Subject";
$l_sendm_mess		 = "Message";
$l_sendm_send		 = "Send";
$l_sendm_sent		 = "Message Sent";

// zoneinfo.php

$l_zi_title		 = "Zone Information";
$l_zi_nexist		 = "This section of space does not exist!";
$l_zi_feds		 = "Federation";
$l_zi_traders		 = "The Free-Trade Coalition";
$l_zi_nobody		 = "Nobody";
$l_zi_war		 = "Contested space";
$l_zi_allow		 = "Allowed";
$l_zi_notallow		 = "Not allowed";
$l_zi_limit		 = "Limited to owner and allies";
$l_zi_ul		 = "Unlimited";
$l_zi_control		 = "You are in control of this zone";
$l_zi_tochange		 = "to change its laws.";
$l_zi_owner		 = "Zone owner";
$l_zi_maxhull		 = "Maximum average tech level allowed";

// zoneedit.php

$l_ze_title		 = "Edit Zone";
$l_ze_notowner		 = "You are not owner of this zone so you can't edit it.";
$l_ze_name		 = "Zone name";
$l_ze_allow		 = "Allow";
$l_ze_attacks		 = "Allow attacking other ships";
$l_ze_genesis		 = "Allow creating new planets";
$l_ze_return		 = "to return to the zone information page";
$l_ze_saved		 = "Your changes have been saved.";

// teams.php

$l_team_title		 = "Alliances";
$l_team_menu		 = "to go back to the Alliances Menu";
$l_team_galax		 = "Alliances present in the Galaxy:";
$l_team_members		 = "Members";
$l_team_coord		 = "Co-ordinator";
$l_team_member		 = "Member";
$l_team_noinvite	 = "Nobody has invited you to join an alliance.";
$l_team_ifyouwant	 = "If you want to join an alliance, send a message to its co-ordinator asking to be invited.";
$l_team_tocreate	 = "to create a new alliance.";
$l_team_injoin		 = "You have been invited to join";
$l_team_tojoin		 = "to join";
$l_team_or		 = "or";
$l_team_reject		 = "to reject the invitation.";
$l_team_ed		 = "Edit";
$l_team_inv		 = "Invite";
$l_team_leave		 = "Leave";
$l_team_eject		 = "Eject";
$l_team_pending		 = "Invitation pending for";
$l_team_noinvites	 = "Nobody has been invited to be part of";
$l_team_confirmleave	 = "Are you sure you want to leave";
$l_team_onlymember	 = "You were the only member, thus [team_name] is no more.";
$l_team_youarecoord	 = "You are the co-ordinator of";
$l_team_relinq		 = "You must relinquish your role to another player.";
$l_team_newc		 = "New co-ordinator:";
$l_team_youveleft	 = "You have left alliance";
$l_team_relto		 = "relinquishing the functions of co-ordinator to";
$l_team_welcome		 = "Welcome to alliance";
$l_team_noinviteto	 = "You have not been invited in to that team.";
$l_team_ejectsure	 = "Are you sure you want to eject";
$l_team_ejected 	 = "has been eject from the alliance!";
$l_team_testing		 = "Testing phase...";
$l_team_pw		 = "Password";
$l_team_entername	 = "Enter the name of the Alliance";
$l_team_enterdesc	 = "Enter a description of the Alliance";
$l_team_hcreated	 = "has been created and you are its leader";
$l_team_alliance	 = "Alliance";
$l_team_selectp		 = "Select the Player you want to invite";
$l_team_isorry		 = "Sorry, but [name] has already been invited to be part of an alliance - only one invitation can be active at any given time";
$l_team_plinvted	 = "Player invited.<BR>You must wait for that player to aknowledge your invitation.";
$l_team_refuse		 = "You have refused the invitation to join";
$l_team_edname		 = "Edit the name of your Alliance";
$l_team_eddesc		 = "Edit the description for your Alliance";
$l_team_hasbeenr	 = "has been renamed.";
$l_team_error		 = "<b><font color=red>An error occured</font></b><br>You are not the leader of this Alliance.";
$l_team_notmember	 = "You are not a member of any alliance";
$l_team_urejected	 = "<B>ATTENTION</B> - you have been ejected from";
$l_team_noalliances	 = "There are no alliances in the Galaxy at this time.";

// ranking.php

$l_ranks_title		 = "Top $max_rank Players";
$l_ranks_none		 = "No Results to show.";
$l_ranks_pnum		 = "Total number of players";
$l_ranks_dships		 = "Players with destroyed ships are not counted.";
$l_ranks_rank		 = "Rank";
$l_ranks_lastlog	 = "Last login";
$l_ranks_good		 = "Good";
$l_ranks_evil		 = "Evil";

// beacon.php

$l_beacon_title		 = "Deploy Space Beacon";
$l_beacon_notpermitted	 = "Deploying space beacons in this sector is not permitted.";
$l_beacon_reads		 = "Present beacon reads";
$l_beacon_none		 = "There presently isn't a beacon in this sector.";
$l_beacon_enter		 = "Enter text for beacon";
$l_beacon_nowreads	 = "Beacon now reads";
$l_beacon_donthave	 = "You do not have a space beacon.";

// emerwarp.php

$l_ewd_title		 = "Use Emergency Warp Device";
$l_ewd_used		 = "Emergency warp device engaged - arrived in sector [sector].";
$l_ewd_none		 = "You do not have an emergency warp device.";

// defence-report.php

$l_sdf_title		 = "Sector Defence Report";
$l_sdf_none		 = "You have no sector defences deployed.";
$l_sdf_type		 = "Type";
$l_sdf_mode		 = "Mode";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_within		 = " in ";
$l_tdr_title    	 = "Trade Routes";
$l_tdr_newtdr   	 = "Click <a href=\"traderoute.php?command=new\">here</a> to create a new trade route";
$l_tdr_modtdrset         = "To modify your global trade settings, click <a href=\"traderoute.php?command=settings\">here</a>";
$l_tdr_confdel  	 = "Click <a href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">here</a> to confirm deletion of the following trade route :";
$l_tdr_noactive 	 = "You do not have any active trade routes to display.";
$l_tdr_curtdr   	 = "Current Trade Routes";
$l_tdr_deltdr   	 = "Delete Trade Route";
$l_tdr_src      	 = "Source";
$l_tdr_srctype  	 = "Src Type";
$l_tdr_dest     	 = "Destination";
$l_tdr_desttype 	 = "Dest Type";
$l_tdr_move     	 = "Move";
$l_tdr_circuit  	 = "Circuit";
$l_tdr_change   	 = "Change";
$l_tdr_portin   	 = "Port in";
$l_tdr_planet   	 = "Planet";
$l_tdr_nonexistance      = "Non-existant planet!";
$l_tdr_na       	 = "N/A";
$l_tdr_cargo    	 = "Cargo";
$l_tdr_none     	 = "None";
$l_tdr_colonists         = "Colonists";
$l_tdr_fighters 	 = "Fighters";
$l_tdr_torps    	 = "Torpedoes";
$l_tdr_escooped 	 = "[tdr_dist_triptime] turns<br>[tdr_dist_scooped] energy scooped";
$l_tdr_warp     	 = "Warp";
$l_tdr_turns    	 = "turns";
$l_tdr_way      	 = "way";
$l_tdr_ways     	 = "ways";
$l_tdr_edit     	 = "Edit";
$l_tdr_del      	 = "Delete";
$l_tdr_nowlink1 	 = "There is no warp link from sector [tdr_src_sector_id] to sector [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "There is no warp link from sector [tdr_dest_sector_id] to sector [tdr_src_sector_id]";
$l_tdr_sportissrc        = "If a special port is source, a planet must be the destination for colonization.";
$l_tdr_notownplanet      = "You can't colonize a planet that you or your team don't own.";
$l_tdr_planetisdest      = "A planet can be a destination only when source is a special port.";
$l_tdr_samecom 		 = "You can't make a traderoute for ports selling the same commodities.";
$l_tdr_sportcom 	 = "You can't sell commodities from a planet in a special port.";
$l_tdr_editerr  	 = "Edit error : trade route not found in DB";
$l_tdr_maxtdr   	 = "Sorry you have reached the maximum number of trade routes allowed.";
$l_tdr_createnew         = "Creating a new";
$l_tdr_editinga 	 = "Editing a";
$l_tdr_traderoute        = "trade route";
$l_tdr_unnamed  	 = "Unnamed";
$l_tdr_cursector         = "You are currently in sector";
$l_tdr_selspoint         = "Please select starting point :";
$l_tdr_port     	 = "Port";
$l_tdr_insector 	 = "in sector";
$l_tdr_selendpoint       = "Please select ending point";
$l_tdr_selmovetype       = "Please select move type";
$l_tdr_realspace         = "Real Space";
$l_tdr_selcircuit        = "Please select circuit";
$l_tdr_oneway   	 = "One way";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] does not seem to be valid.";
$l_tdr_bothways 	 = "Both ways";
$l_tdr_create   	 = "Create";
$l_tdr_modify   	 = "Modify";
$l_tdr_returnmenu        = "Click <a href=traderoute.php>here</a> to return to the trade routes menu.";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] is not a valid port.";
$l_tdr_errnoport         = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnosrc    	 = "Error : specified source planet doesn't exist.";
$l_tdr_errnotownnotsell  = "Error : you do not own planet [tdr_source_name] in sector [tdr_source_sector_id] and planet is not selling.";
$l_tdr_errnotvaliddestport= "Error : the destination port [tdr_port_id] is not a valid port.";
$l_tdr_errnoport2        = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnodestplanet   = "Error : specified destination planet does not exist.";
$l_tdr_errnotownnotsell2 = "Error : you do not own planet [tdr_dest_name] in sector [tdr_dest_sector_id] and planet is not selling.";
$l_tdr_newtdrcreated     = "New trade route created!";
$l_tdr_tdrmodified       = "Trade route modified!";
$l_tdr_doesntexist       = "That trade route doesn't exist!";
$l_tdr_notowntdr         = "You do not own that traderoute!";
$l_tdr_tdrdeleted        = "Trade route deleted.";
$l_tdr_globalset         = "Global trade route settings";
$l_tdr_tdrsportsrc       = "For trade routes having a special port as a source, trade";
$l_tdr_tdrescooped       = "For real space trade routes, what to do with the energy scooped?";
$l_tdr_trade    	 = "Trade";
$l_tdr_keep    	 	 = "Keep";
$l_tdr_save    	 	 = "Save";
$l_tdr_globalsetsaved    = "Global trade route settings saved.";
$l_tdr_engagenonexist    = "Tried to engage a non-existing trade route!";
$l_tdr_invalidspoint     = "Starting port does not seem to be valid!";
$l_tdr_inittdr  	 = "You are not in sector [tdr_source_id]! You must be in starting sector before you initiate a trade route!";
$l_tdr_invalidsrc        = "Source planet doesn't seem to be a valid planet!";
$l_tdr_inittdrsector     = "You are not in sector [tdr_source_sector_id]! You must be in starting sector before you initiate a trade route!";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector [tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed for outsiders";
$l_tdr_tdrres  		 = "Trade Route Results";
$l_tdr_bought  		 = "Bought";
$l_tdr_nothingtotrade    = "Nothing to trade";
$l_tdr_sold   	  	 = "Sold";
$l_tdr_ore    		 = "Ore";
$l_tdr_portisfull        = "Port is full";
$l_tdr_goods    	 = "goods";
$l_tdr_organics 	 = "organics";
$l_tdr_energy   	 = "energy";
$l_tdr_portisempty       = "Port is empty";
$l_tdr_loaded   	 = "Loaded";
$l_tdr_nothingtoload     = "Nothing to load";
$l_tdr_scooped  	 = "Scooped";
$l_tdr_dumped   	 = "Dumped";
$l_tdr_planetisovercrowded= "Planet is overcrowded";
$l_tdr_nothingtodump     = "Nothing to dump";
$l_tdr_onlyonewaytdr     = "Did nothing, traderoute was one way only";
$l_tdr_profit 		 = "Profit";
$l_tdr_cost   		 = "Cost";
$l_tdr_totalprofit       = "Total profit";
$l_tdr_totalcost         = "Total cost";
$l_tdr_credits  	 = "Credits";
$l_tdr_turnsused         = "Turns used";
$l_tdr_turnsleft         = "Turns left";
$l_tdr_notowner = "You do not own this trade route";

// IGB.php

$l_igb_credit_symbol = "C";
$l_igb_title    = "The Intergalactic Bank";
$l_igb_humor    = "All your base are belong to us.";
$l_igb_malfunction      = "This IGB terminal is malfunctionning. The Intergalatic Bank wishes to apologize for any inconvenience.";
$l_igb_quit     = "Quit";
$l_igb_login    = "Login";
$l_igb_welcometoigb     = "Welcome to this Intergalactic Banking Terminal";
$l_igb_accountholder    = "Account Holder";
$l_igb_shipaccount      = "Ship Account";
$l_igb_igbaccount       = "IGB Account";
$l_igb_operations       = "Operations";
$l_igb_withdraw = "Withdraw";
$l_igb_deposit  = "Deposit";
$l_igb_transfer = "Transfer";
$l_igb_back     = "Back";
$l_igb_logout   = "Logout";
$l_igb_withdrawfunds    = "Withdraw Funds";
$l_igb_fundsavailable   = "Funds available";
$l_igb_selwithdrawamount        = "Please select amount to withdraw";
$l_igb_depositfunds     = "Deposit Funds";
$l_igb_seldepositamount = "Please select amount to deposit";
$l_igb_transfertype     = "Transfer Type";
$l_igb_toanothership    = "To another ship";
$l_igb_shiptransfer     = "Ship Transfer";
$l_igb_fromplanet       = "From a planet to another";
$l_igb_unnamed  = "Unnamed";
$l_igb_in       = "in";
$l_igb_none     = "None";
$l_igb_destination      = "Destination";
$l_igb_planettransfer   = "Planet Transfer";
$l_igb_sendyourself     = "You can't send money to yourself!";
$l_igb_unknowntargetship        = "Unknown target ship!";
$l_igb_min_turns        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns2       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_maxtransfer      = "Maximum transfer allowed";
$l_igb_unlimited        = "Unlimited";
$l_igb_maxtransferpercent       = "Maximum transfer allowed ([igb_percent]% of net worth)";
$l_igb_recipient        = "Recipient";
$l_igb_seltransferamount        = "Please select amount to transfer";
$l_igb_transferrate     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errplanetsrcanddest      = "The same planet can't be both source and destination.";
$l_igb_errunknownplanet = "DB Error! Unknown Planet!";
$l_igb_errnotyourplanet = "You can't transfer money from/to a planet you do not own.";
$l_igb_srcplanet        = "Src -> Planet";
$l_igb_destplanet       = "Dst -> Planet";
$l_igb_transferrate2     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errsendyourself  = "You can't send money to yourself!";
$l_igb_min_turns3        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns4       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait2 = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_invalidtransferinput     = "Invalid input for transfer.";
$l_igb_nozeroamount     = "Amount to transfer must not be zero.";
$l_igb_notenoughcredits = "You do not have enough credits to perform this operation.";
$l_igb_amounttoogreat   = "The amount you entered was greater than your maximum transfer allowed.";
$l_igb_transfersuccessful       = "Transfer Successful";
$l_igb_creditsto        = "credits have been transferred to";
$l_igb_transferamount   = "Transfer Amount";
$l_igb_transferfee      = "Transfer Fee";
$l_igb_amounttransferred        = "Amount Transferred";
$l_igb_notenoughcredits2        = "There are not enough credits on source planet to complete that transaction.";
$l_igb_to       = "to";
$l_igb_ctransferredfrom = "credits have been transferred from";
$l_igb_invaliddepositinput      = "Invalid input for deposit.";
$l_igb_nozeroamount2    = "Amount to deposit must not be zero.";
$l_igb_operationsuccessful      = "Operation successful";
$l_igb_creditstoyou     = "Credits have been transfered to your IGB account.";
$l_igb_accounts = "Accounts";
$l_igb_invalidwithdrawinput     = "Invalid input for withdraw.";
$l_igb_nozeroamount3    = "Amount to withdraw must not be zero.";
$l_igb_creditstoyourship        = "Credits have been transfered to your ship account.";
$l_igb_igberrreport     = "IGB Error Report";
$l_igb_source   = "Source";
$l_igb_loans = "Loans";
$l_igb_loanstatus = "Loans Status";
$l_igb_currentloan = "Total Current Loan";
$l_igb_maxloanpercent = "Maximum loan allowed ([igb_percent]% of net worth)";
$l_igb_loanamount = "Enter the loan amount";
$l_igb_borrow = "Borrow";
$l_igb_loanrates     = "All loans incur a one-time fee of [factor]% of total loan amount. Additionally, you will be charged [interest]% in interests each turn until you repay.";
$l_igb_invalidamount = "You entered an invalid amount.";
$l_igb_notwoloans = "You cannot take a loan without repaying your first one.";
$l_igb_loantoobig = "You are not allowed to borrow that many credits.";
$l_igb_takenaloan = "Taken a Loan";
$l_igb_loancongrats = "Congratulation! You have just taken a loan with the friendliest banking consortium around!";
$l_igb_loantransferred = "Amount transferred to your ship account";
$l_igb_loanfee = "One-time loan fee";
$l_igb_amountowned = "Total amount owned to the IGB";
$l_igb_loanreminder = "Friendly reminder: if you have not repayed your loan in totality in [hours]h [mins]m, we will be forced to render your ship's account invalid in special ports.<br><br>\"The IGB, fullfiller of your dreams\"";
$l_igb_loantimeleft = "Time left until full payment is due";
$l_igb_loanlate = "Payment is late!";
$l_igb_repayamount = "Enter the amount to repay";
$l_igb_repay = "Repay";
$l_igb_notrepay = "You have no loans to repay";
$l_igb_notenoughrepay = "You do not have enough credits in your ship account to perform this operation.";
$l_igb_payloan = "Loan Payment";
$l_igb_loanthanks = "Your payment has been received. Thank you for doing business with the IGB.";
$l_igb_credsconsol = "Src -> Total Credits to consolidate";
$l_igb_transferrate3     = "Current rate for consolidating is [igb_num_percent]% of total amount. It will automatically be deduced from the amount consolidated. The transfer will cost one turn for every [nbplanets] planets affected.";
$l_igb_currentpl = "Credits on planet";
$l_igb_consolrates = "You can specify a credit range. Planets with less credits than Minimum and with more credits than Maximum will not be affected. Set to 0 for no limits";
$l_igb_minimum = "Minimum";
$l_igb_maximum = "Maximum";
$l_igb_planetconsolidate = "Planet Consolidate";
$l_igb_compute = "Compute";
$l_igb_plaffected = "Total planets affected";
$l_igb_turncost = "Total turns cost";
$l_igb_consolidate = "Consolidate";
$l_igb_conspl = "Consolidate Credits to a single planet";
$l_igb_notenturns = "You do not have enough turns to perform this operation";

// combat.php

$l_cmb_atleastoneturn   = "You need at least one turn to attack a planet.";
$l_cmb_shipenergybb     = "Ship energy before beams";
$l_cmb_shipenergyab     = "Ship energy after beams";
$l_cmb_shipenergyas     = "Ship energy after shields";
$l_cmb_shiptorpsbtl     = "Ship torpedos before torp launch";
$l_cmb_shiptorpsatl     = "Ship torpedos after torp launch";
$l_cmb_planettorpdamage = "Planet torp damage";
$l_cmb_attackertorpdamage       = "Attacker torp damage";
$l_cmb_beams    = "Beams";
$l_cmb_fighters = "Fighters";
$l_cmb_shields  = "Shields";
$l_cmb_torps    = "Torps";
$l_cmb_torpdamage       = "Torp Damage";
$l_cmb_armor    = "Armor";
$l_cmb_you      = "You";
$l_cmb_planet   = "Planet";
$l_cmb_combatflow       = "Combat Flow";
$l_cmb_defender = "Defender";
$l_cmb_attackingplanet  = "Attacking planet in sector";
$l_cmb_youfireyourbeams = "You fire your beams";
$l_cmb_defenselost      = "Planetary defense lost [cmb_planetfighters] fighters to your beams";
$l_cmb_defenselost2     = "Planetary Defense lost [cmb_attackerbeams] fighters, but there are more coming!";
$l_cmb_planetarybeams   = "Planetary beams destroy [cmb_temp] of your fighters";
$l_cmb_planetarybeams2   = "Planetary beams destroy [cmb_planetbeams] of your fighters";
$l_cmb_youdestroyedplanetshields        = "Your beams have destroyed the planetary shields";
$l_cmb_beamsexhausted   = "You destroy [cmb_attackerbeams] planetary shields before your beams are exhausted";
$l_cmb_breachedyourshields      = "Planetary beams have breached your shields";
$l_cmb_destroyedyourshields     = "Planetary beams have destroyed [cmb_planetbeams] of your shields";
$l_cmb_breachedyourarmor        = "Planetary beams have breached your armor";
$l_cmb_destroyedyourarmor       = "Planetary beams have destroyed [cmb_planetbeams] points of armor";
$l_cmb_torpedoexchangephase     = "Torpedo Exchange Phase";
$l_cmb_nofightersleft   = "Your torpedos destroy [cmb_planetfighters] planetary fighters, no fighters are left";
$l_cmb_youdestroyfighters       = "Your torpedos destroy [cmb_attackertorpdamage] planetary fighters";
$l_cmb_planettorpsdestroy       = "Planetary torpedos destroy [cmb_temp] of your fighters";
$l_cmb_planettorpsdestroy2      = "Planetary torpedos destroy [cmb_planettorpdamage] of your fighters";
$l_cmb_torpsbreachedyourarmor   = "Planetary torpedos have breached your armor";
$l_cmb_planettorpsdestroy3      = "Planetary torpedos have destroyed [cmb_planettorpdamage] points of armor";
$l_cmb_youdestroyedallfighters  = "Your torpedos have destroyed all the planetary fighters";
$l_cmb_youdestroyplanetfighters = "Your torpedos destroy [cmb_attackertorpdamage] planetary fighters";
$l_cmb_fightercombatphase       = "Fighter Combat Phase";
$l_cmb_youdestroyedallfighters2  = "Your fighters have destroyed all the planetary fighters.";
$l_cmb_youdestroyplanetfighters2        = "Your fighters have destroyed [cmb_attackerfighters] planetary fighters";
$l_cmb_allyourfightersdestroyed = "All your fighters were destroyed";
$l_cmb_fightertofighterlost     = "You lost [cmb_planetfighters] fighters in fighter to fighter combat";
$l_cmb_youbreachedplanetshields = "Your fighters have breached the planetary shields";
$l_cmb_shieldsremainup  = "Your fighters destroyed [cmb_attackerfighters] planetary shields, but they remain up";
$l_cmb_fighterswarm     = "Planetary fighters swarm your ship, your armor has been breached";
$l_cmb_swarmandrepel    = "Planetary fighters swarm your ship, but your armor repels them";
$l_cmb_engshiptoshipcombat      = "Engaging in Ship to Ship combat.";
$l_cmb_shipdock = "There are [cmb_shipsonplanet] ships docked at Spacedock!";
$l_cmb_approachattackvector     = "is approaching on an attack vector";
$l_cmb_noshipsdocked    = "There are NO ships docked at Spacedock!";
$l_cmb_yourshipdestroyed        = "Your ship has been destroyed!";
$l_cmb_escapepod        = "Luckily you have an escape pod!";
$l_cmb_finalcombatstats = "Final Combat Stats";
$l_cmb_youlostfighters  = "You lost [cmb_fighters_lost] out of [cmb_playerinfo_ship_fighters] total fighters.";
$l_cmb_youlostarmorpoints       = "You lost [cmb_armor_lost] out of [cmb_playerinfo_armour_pts] total armor points, you have [cmb_attackerarmor] points remaining.";
$l_cmb_energyused       = "You used [cmb_energy_lost] energy, from a total of [cmb_playerinfo_ship_energy] energy.";
$l_cmb_planetdefeated   = "Planet defeated";
$l_cmb_citizenswanttodie        = "The citizens of this planet have decided they'd rather die than serve a pathetic ruler like you. They use a laser drill to dig a hole to the planet's core. You barely have time to escape into orbit before the whole planet is reduced to a ball of molten lava.";
$l_cmb_youmaycapture    = "You may <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> the planet or just leave it undefended.";
$l_cmb_youmaycapture2   = "You may <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> the planet or just leave it undefended.";
$l_cmb_planetnotdefeated        = "Planet not defeated";
$l_cmb_planetstatistics = "Planet statistics";
$l_cmb_fighterloststat  = "Fighters lost: [cmb_fighters_lost] out of [cmb_planetinfo_fighters] ([cmb_planetfighters] alive)";
$l_cmb_energyleft       = "Energy left";
$l_cmb_startingstats    = "Starting stats";
$l_cmb_statattackerbeams        = "Attackerbeams";
$l_cmb_statattackerfighters     = "Attackerfighters";
$l_cmb_statattackershields      = "Attackershields";
$l_cmb_statattackertorps        = "Attackertorps";
$l_cmb_statattackerarmor        = "Attackerarmor";
$l_cmb_statattackertorpdamage   = "Attackertorpdamage";
$l_cmb_isattackingyou   = "is attacking you";
$l_cmb_beamexchange     = "Beam exchange";
$l_cmb_beamsdestroy     = "Your beams destroy [cmb_lost] fighters";
$l_cmb_beamsdestroy2    = "Your beams destroy [cmb_attackerbeams] fighters, but there are more coming";
$l_cmb_nobeamsareleft   = "You have no beams left to destroy the incoming fighters!";
$l_cmb_beamshavenotarget        = "Your beams have no fighter targets to destroy";
$l_cmb_fighterdestroyedbybeams  = "[cmb_targetinfo_ship_name] destroyed [cmb_lost] of your fighters with beams<BR>";
$l_cmb_beamsdestroystillhave    = "[cmb_targetinfo_ship_name] destroyed [cmb_targetbeams] of your fighters with beams, but you still have [cmb_attackerfighters] left";
$l_cmb_fighterunhindered        = "Your fighters attack unhindered, the enemy has no beams left.";
$l_cmb_youhavenofightersleft    = "You have no fighters left to attack with";
$l_cmb_breachedsomeshields      = "You have breached [cmb_targetinfo_ship_name]'s shields with your beams";
$l_cmb_shieldsarehitbybeams     = "[cmb_targetinfo_ship_name]'s shields are hit for [cmb_attackerbeams] damage by your beams";
$l_cmb_nobeamslefttoattack      = "You have no beams left to attack [cmb_targetinfo_ship_name]'s shields";
$l_cmb_yourshieldsbreachedby    = "[cmb_targetinfo_ship_name]'s beams have breached your shields";
$l_cmb_yourshieldsarehit        = "[cmb_targetinfo_ship_name]'s beams have hit your shields for [cmb_targetbeams] damage.";
$l_cmb_hehasnobeamslefttoattack = "[cmb_targetinfo_ship_name] has no beams left to attack your shields";
$l_cmb_yourbeamsbreachedhim     = "Your beams have breached [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourbeamshavedonedamage  = "Your beams have done [cmb_attackerbeams] damage to [cmb_targetinfo_ship_name]'s armor";
$l_cmb_nobeamstoattackarmor     = "You have no beams left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourarmorbreachedbybeams = "Your armor has been breached by [cmb_targetinfo_ship_name]'s beams";
$l_cmb_yourarmorhitdamaged      = "Your armor is hit for [cmb_targetbeams] damage by [cmb_targetinfo_ship_name]'s beams";
$l_cmb_torpedoexchange  = "Torpedo exchange";
$l_cmb_hehasnobeamslefttoattackyou      = "[cmb_targetinfo_ship_name] has no beams left to attack your armor";
$l_cmb_yourtorpsdestroy = "Your torpedos destroy [cmb_lost] of [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_yourtorpsdestroy2        = "Your torpedos destroy [cmb_attackertorpdamage] of [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_youhavenotorpsleft       = "You have no torpedo's left to attack [cmb_targetinfo_ship_name]'s fighters.";
$l_cmb_hehasnofighterleft       = "[cmb_targetinfo_ship_name] has no fighters left for you to destroy with torpedos";
$l_cmb_torpsdestroyyou  = "[cmb_targetinfo_ship_name]'s torpedo's destroy [cmb_lost] of your fighters";
$l_cmb_someonedestroyedfighters = "[cmb_targetinfo_ship_name] destroyed [cmb_targettorpdmg] of your fighters with torpedos";
$l_cmb_hehasnotorpsleftforyou   = "[cmb_targetinfo_ship_name] has no torpedo's left to attack your fighters";
$l_cmb_youhavenofightersanymore = "You have no fighters left to be destroyed by [cmb_targetinfo_ship_name]'s torpedo's";
$l_cmb_youbreachedwithtorps     = "You have breached [cmb_targetinfo_ship_name]'s armor with your torpedos";
$l_cmb_hisarmorishitbytorps     = "[cmb_targetinfo_ship_name]'s armor is hit for [cmb_attackertorpdamage] damage by your torpedos";
$l_cmb_notorpslefttoattackarmor = "You have no torpedo's left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourarmorbreachedbytorps = "Your armor has been breached by [cmb_targetinfo_ship_name]'s torpedos";
$l_cmb_yourarmorhitdmgtorps     = "Your armor is hit for [cmb_targettorpdmg] damage by [cmb_targetinfo_ship_name]'s torpedos";
$l_cmb_hehasnotorpsforyourarmor = "[cmb_targetinfo_ship_name] has no torpedo's left to attack your armor";
$l_cmb_fightersattackexchange   = "Fighters Attack exchange";
$l_cmb_enemylostallfighters     = "[cmb_targetinfo_ship_name] lost all fighters.";
$l_cmb_helostsomefighters       = "[cmb_targetinfo_ship_name] lost [cmb_attackerfighters] fighters.";
$l_cmb_youlostallfighters       = "You lost all fighters.";
$l_cmb_youalsolostsomefighters  = "You lost [cmb_targetfighters] fighters.";
$l_cmb_hehasnofightersleftattack        = "[cmb_targetinfo_ship_name] has no fighters left for your fighters to attack";
$l_cmb_younofightersattackleft  = "You have no fighters left to attack [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_youbreachedarmorwithfighters     = "You have breached [cmb_targetinfo_ship_name]'s armor with your fighters";
$l_cmb_youhitarmordmgfighters   = "You hit [cmb_targetinfo_ship_name]'s armor for [cmb_attackerfighters] damage with your fighters";
$l_cmb_youhavenofighterstoarmor = "You have no fighters left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_hasbreachedarmorfighters = "[cmb_targetinfo_ship_name] has breached your armor with fighters";
$l_cmb_yourarmorishitfordmgby   = "Your armor is hit for [cmb_targetfighters] damage by [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_nofightersleftheforyourarmor     = "[cmb_targetinfo_ship_name] has no fighters left to attack your armor";
$l_cmb_hehasbeendestroyed       = "[cmb_targetinfo_ship_name] has been destroyed";
$l_cmb_escapepodlaunched        = "An escape pod was launched!";
$l_cmb_yousalvaged      = "You salvaged [cmb_salv_ore] units of ore, [cmb_salv_organics] units of organics, [cmb_salv_goods] units of goods, and salvaged [cmb_salvage_rate]% of the ship for [cmb_salvage] credits.<BR>Your rating changed by [cmb_number_rating_change] points.";
$l_cmb_youdidntdestroyhim       = "You did not destory [cmb_targetinfo_ship_name]";
$l_cmb_shiptoshipcombatstats    = "Ship to Ship combat stats";

// check_mines.php

$l_chm_youhitsomemines  = "You hit [chm_roll] mines!";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] hit [chm_roll] mines in sector [chm_sector].";
$l_chm_youlostminedeflectors    = "You lost [chm_roll] mine deflectors.";
$l_chm_youlostallminedeflectors = "You lost all your mine deflectors.";
$l_chm_youhadnominedeflectors  = "You had no mine deflectors.";
$l_chm_yourshieldshitforminesdmg        = "Your shields are hit for [chm_mines_left] damage.";
$l_chm_yourshieldsaredown       = "Your shields are down!";
$l_chm_youlostallyourshields    = "You lost all your shields!";
$l_chm_yourarmorhitforminesdmg  = "Your armour is hit for [chm_mines_left] damage.";
$l_chm_yourhullisbreached       = "Your hull is breached!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] was destroyed by your mines in sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Your ship has been destroyed!";
$l_chm_luckescapepod    = "Luckily you have an escape pod!";

// check_fighters.php

$l_chf_youretreatback   = "You retreat back to your previous location";
$l_chf_notenoughcreditstoll     = "You do not have enough credits to pay the toll.";
$l_chf_movefailed       = "Move failed.";
$l_chf_youpaidsometoll  = "You paid [chf_tollstring] credits for the toll.";
$l_chf_thefightersdetectyou     = "The fighters detect you!";
$l_chf_therearetotalfightersindest      = "There are [chf_total_sector_fighters] fighters in your destination sector.";
$l_chf_creditsdemanded  = "They demand [chf_number_fighterstoll] credits to enter this sector.";
$l_chf_youcanretreat    = "You can <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Retreat</B> - Will cost an extra turn.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Pay</B> the toll and enter without harm from the fighters.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Fight</B> - you must defeat all the fighters to enter the sector.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Cloak</B> - Use your cloaking device and try to avoid the fighters.<BR></INPUT>";
$l_chf_go       = "Go";

// mines.php

$l_mines_title			="Deploy Sector Mines & Fighters";
$l_mines_noturn		 	="You need at least one turn to deploy sector defences.";
$l_mines_nopermit		="Deploying Mines and Fighters in this sector is not permitted.";
$l_mines_nodeploy		="Can not deploy here. Another Ship or Alliance has mines or fighters in this sector.";
$l_mines_info1			="You are presently in sector [sector]. There are [mines] mines and [fighters] fighters here.";
$l_mines_info2			="You have [mines] mines and [fighters] fighters available to deploy";
$l_mines_deploy			="Deploy";
$l_mines_deployed		="Deployed";
$l_mines_att			="Attack";
$l_mines_toll			="Toll";
$l_mines_notorps		="You do not have enough torpedos.";
$l_mines_nofighters		="You do not have enough fighters";
$l_mines_dmines			="Deployed [mines] mines.";
$l_mines_dfighter		="Deployed [fighters] fighters in [mode] mode.";
$l_mines_fmode			="Fighter mode";

//alliance-planets.php

$l_teamplanet_title		="Alliance Planet Report";
$l_teamplanet_notally		="You aren't in an alliance.";
$l_teamplanet_personal		="Show personal planets";
$l_teamplanet_noplanet		="Your alliance has no planets";

$l_feedback_title		="Send Feedback";
$l_feedback_to			="TO:";
$l_feedback_from		="FROM:";
$l_feedback_topi		="SUBJECT:";
$l_feedback_feedback		="Feedback";
$l_feedback_message		="MESSAGE:";
$l_feedback_messent		="Message Sent";
$l_feedback_subj		="WTW Feedback";
$l_feedback_info		="Please send feedback in english only"; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Corporation Menu";
$l_corpm_tocorp			="Planet is now a Corporate Planet!";
$l_corpm_topersonal		="Planet is now a Personal Planet!";
$l_corpm_exploit		="You intercept a garbled borg message on your scanner... you should probably start worrying...";


// login.php login2.php
$l_login_title			="Login"; 
$l_login_email			="E-mail Address:";
$l_login_pw			="Password:";
$l_login_chooseres		="Unable to determine your screen resolution. Please choose the best fit:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new.php\">here</A>.";
$l_login_prbs			= "Problems?";
$l_login_emailus		= "E-mail us";
$l_login_sclosed		= "Server Closed";
$l_login_closed_message		="Server closed until further notice.";
$l_login_title2			="Login Phase Two"; 
$l_login_banned			="<b>You have been banned from this game by the administrator. You are no longer welcome to play on this server. Next time, behave.</b>";
$l_login_died			="Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php>here</A> to continue with a new ship.";
$l_login_newbie			="Due to the seriousness of this crime and the vicious attack against you, the Federation has graciously decided to provide a free of charge cloning from your remains.  Sadly, even in this day and age, new clones can not own property, aside from the basics to make a living.  You will be provided with a basic ship and a few credits to get you started.  Hopefully your next life will be better.";
$l_login_newlife		="Click <A HREF=main.php>here</A> to continue in a new life.";
$l_login_looser			="You had no escape pod, and due to your modest success in this life, the Federation declines to clone you.  Your remains should eventually fall into a gravity well, hopefully to be used to create life elsewhere... several billion years from now.<BR><BR> Better luck next game...";
$l_login_4gotpw1		= "The password you entered is incorrect.<BR><BR>  If you have forgotten your password, ";
$l_login_4gotpw2		= "to have it e-mailed to you.<BR><BR>  Otherwise,";
$l_login_4gotpw3		= "to try again.  Attempt logged with IP address of";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new.php>here</A>.";
$l_login_lang = "Language";
$l_login_settings = "Game Settings";
$l_login_change = "Change";

// new.php new2.php
$l_new_title			= "Create New Player"; 
$l_new_title2			= "Create New Player Phase Two"; 
$l_new_shipname			= "Ship Name";
$l_new_pname			= "Player Character Name";
$l_new_info			= "We promise not to give out (or sell) your e-mail address to anyone.  It is required though, to send you your server generated password..";
$l_new_closed_message		="Game closed for tournament play";
$l_new_blank			="E-mail, ship name, and character name may not be blank.";
$l_new_inuse			="E-mail address is already in use.";
$l_new_4gotpw1			="If you have forgotten your password,";
$l_new_4gotpw2			="to have it e-mailed to you.";
$l_new_inusechar		="Character name $character, is already in use.";
$l_new_inuseship		="Ship name $shipname, is already in use.";
$l_new_pwsent			="Password has been sent to ${HTTP_POST_VARS['username']}.";
$l_new_login			="to go to the login screen.";
$l_new_err			="Please go back or <a href=new.php>click here</a> and try again.";
$l_new_topic			="Traders Password";
$l_new_message			="Greetings,\n\nSomeone from the IP address $ip requested that your password for Traders be sent to you.\n\nYour password is: [pass]\n\nThank you\n\nThe Traders web team.";

// logout.php

$l_logout_score			="You current score is";
$l_logout_text			="[name] is now logged out.  Click <A HREF=index.php>here</A> to return to game.";

// mail.php

$l_mail_title			="Mail Password"; 
$l_mail_noplayer		="No Such Player! - Create a new player <a href=new.php>here</a>.";
$l_mail_sent			="Password has been sent to";
$l_mail_topic			="$game_name Password";
$l_mail_message			="Greetings,\n\nSomeone from the IP address $ip requested that your password for $game_name be sent to you.\n\nYour password is: [pass]\n\nThank you\n\nThe $game_name web team.";

// global_funcs.php

$l_global_mmenu			="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin		="Click <A HREF=login.php>here</A> to return to the login screen.";
$l_global_needlogin		="You need to log in, click <A HREF=login.php>here</A>.";
$l_global_died			="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone		="Zone is now a War Zone!";
$l_global_nzone			="Zone is a neutral zone.";
$l_global_team			="Zone now belongs to alliance";
$l_global_player		="Zone now belongs to player";

// texts for the news flashes

$l_news_planets		  = " planets";
$l_news_cols		      = " Million colonists";
$l_news_p_headline = "[player]\'s Empire now has ";

$l_killheadline=" was killed in an accident";
$l_news_killed = "[name] was killed in a tragic accident today. How heroic - captain [name] was the last member on board of his ship, when he noticed there was no escape pod left for him. May he rest in peace!";
$l_news_p_text5		= "The rising empire of [name] now has five planets, the BNN will watch the actions of [name] more closely in the future!";
$l_news_p_text10		= "The growing empire of [name] now controls ten planets, Reports of BNN say that further expansion of [name] might lead to war!";
$l_news_p_text25		= "The huge empire of [name] colonized 25 planets already, in an interview, [name] announced that he might consider slowing down his expansion in the future!";
$l_news_p_text50		= "The enormous vast empire of [name], represented by 50 planets in the whole galaxy is getting a threatening strength. One of the BNN reporters found out that [name] is upgrading his ship planning a major war. In an interview [name] announced that is done on defence purpose only!";
$l_news_c_text25		= "The rising empire of [name] now has 25 million colonists, the BNN will watch the actions of [name] more closely in the future, but its highly obvious that birthrates are going to explode!";
$l_news_c_text100		= "The aspiring empire of [name] now has 100 million colonists, after an explosion of birth rates, [name] colonies seemed to be a good place for families to settle!";
$l_news_c_text500		= "The large empire of [name] now has 500 million colonists, [name] said in an interview that colonization of the galaxy has just yet begun";
$l_news_c_text1000		= "The humongous empire of [name] now has one billion colonists, BNN reporters found out that [name] is in possesion of some weird cloning mechanism allowing him to breed new colonists in huge amounts. With this amount of colonists, the econmic strength of this empire is enormous, BNN hopes that [name] does not spend his money on warfare";

// Options.php

$l_opt_title = "Options";
$l_opt_chpass = "Change password";
$l_opt_curpass = "Current password:";
$l_opt_newpass = "New password:";
$l_opt_newpagain = "New password (again):";
$l_opt_userint = "User interface";
$l_opt_usenew = "Use new layout?";
$l_opt_lang = "Language";
$l_opt_select = "Select One:";
$l_opt_enabled = "Enabled";
$l_opt_save = "Save";

// Option2.php

$l_opt2_title = "Save Options";
$l_opt2_passunchanged = "Password was left unchanged.<BR><BR>";
$l_opt2_srcpassfalse = "Original password incorrect. Password was left unchanged.<BR><BR>";
$l_opt2_newpassnomatch = "New password fields do not match. Password was left unchanged.<BR><BR>";
$l_opt2_passchanged = "Password changed.<BR><BR>";
$l_opt2_passchangeerr = "Error changing password<BR><BR>";
$l_opt2_userintup = "User interface setting updated.<BR><BR>";
$l_opt2_userintfail = "Failed to update user interface setting.<BR><BR>";
$l_opt2_chlang = "Language has been set to [lang].<p>";
$l_opt2_dhtmlup = "Dynamic html setting updated.<BR><BR>";
$l_opt2_dhtmlfail = "Failed to update dynamic html setting.<BR><BR>";

// Presets.php

$l_pre_title = "Change Realspace Presets";
$l_pre_exceed = "Preset [preset] exceeds universe max of [sector_max]. No presets saved.<BR><BR>"; 
$l_pre_set = "Preset 1 set to [preset1], preset 2 set to [preset2] and preset 3 set to [preset3].<BR><BR>";
$l_pre_save = "Save";

// Mailto.php

$l_mt_title = "Send Message";
$l_mt_from = "From:";
$l_mt_subject = "Subject:";
$l_mt_message = "Message:";
$l_mt_sent = "Message sent";
$l_mt_send = "Send";

// sector_fighters.php
$l_sf_attacking = "Sector defence fighters are attacking you!<BR>";
$l_sf_destfight = "Your beams destroyed [lost] fighters<BR>";
$l_sf_destfightb = "Your beams destroyed [lost] fighters<BR>";
$l_sf_torphit = "Torpedoes hit:";
$l_sf_destfightt = "Your torpedoes destroyed [lost] fighters<BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "You destroyed all the fighters.<BR>";
$l_sf_destfightt2 = "You destroyed [lost] fighters.<BR>";
$l_sf_lostfight = "You lost all fighters.<BR>";
$l_sf_lostfight2 = "You lost [lost] fighters.<BR>";
$l_sf_armorbreach = "Your armour is breached!<BR>";
$l_sf_armorbreach2 = "Your armour is hit for [lost] damage.<BR>";
$l_sf_sendlog = "[player] destroyed [lost] sector defence fighters in sector [sector].";
$l_sf_lreport = "You lost [armor] armour points, [fighters] fighters, and used [torps] torpedoes.<BR><BR>";
$l_sf_shipdestroyed = "Your ship has been destroyed!<BR><BR>";
$l_sf_sendlog2 = "Sector defence fighters destroyed [player] in sector [sector].";
$l_sf_escape = "Luckily you have an escape pod!<BR><BR>";

// Zone names

$l_zname[1] = "Unchartered space";
$l_zname[2] = "Federation space";
$l_zname[3] = "Free-trade space";
$l_zname[4] = "War Zone";

// ADDITION TO warpedit2.php

$l_warp_cantsame = "You can't create a link when the source is the same as the destination.";

// Bounty
$l_by_title = "Bounties";
$l_by_noturn = "You need at least one turn to place or modify a bounty.";
$l_by_amount = "Bounty Amount";
$l_by_place = "Place Bounty";
$l_by_nobounties = "There are currently no bounties.";
$l_by_bountyon = "Bounty On";
$l_by_placedby = "Placed by";
$l_by_thefeds  = "The Federation";
$l_by_cancel   = "Cancel";
$l_by_yourself = "You can not place a bounty on your self.";
$l_by_notenough = "You do not have enough credits to place a bounty of that amount.";
$l_by_toomuch   = "You can not place that bounty. Maximum bounty allowed on another player is $percent percent of your net worth";
$l_by_zeroamount = "Bounties must be greater than 0 credits.";
$l_by_placed     = "The bounty has been placed.";
$l_by_nobounty = "That bounty no longer exists.";
$l_by_notyours = "That bounty was not placed by you.";
$l_by_canceled = "The bounty has been canceled.";
$l_by_action   = "Action";
$l_by_placebounty = "Place or view bounties.";
$l_by_moredetails = "Click on the name for more details.";
$l_by_fedbounty = "Attacking this player would result in The Federation placing a bounty on you.";
$l_by_fedbounty2 = "The Federation does not approve of attacking much smaller ships. It has placed a bounty on you.";
$l_by_notexists = "The player you are putting the bounty on does not exist.";
$l_by_destroyed = "You can not place a bounty on a player with a destroyed ship.";
$l_log_text[LOG_BOUNTY_CLAIMED] = "You claimed a bounty of [amount] credits for the destruction of the ship belonging to [bounty_on]. The bounty was placed by [placed_by].";
$l_log_title[LOG_BOUNTY_CLAIMED] = "Bounty Claimed.";
$l_log_text[LOG_BOUNTY_PAID] = "Your bounty on [bounty_on] has been paid for the amount of [amount] credits.";
$l_log_title[LOG_BOUNTY_PAID] = "Bounty Paid.";
$l_log_text[LOG_BOUNTY_CANCELLED] = "Your bounty on [bounty_on] for the amount of [amount] credits has been refunded.";
$l_log_title[LOG_BOUNTY_CANCELLED] = "Bounty Refunded.";
$l_log_text[LOG_SPACE_PLAGUE] = "Your planet [name] in sector [sector] has been hit by Space Plague. [percentage] percent of the colonists were killed.";
$l_log_title[LOG_SPACE_PLAGUE] = "Space Plague!";
$l_log_text[LOG_PLASMA_STORM] = "Your planet [name] in sector [sector] has been hit by a Plasma Storm. All stored Energy has been lost.";
$l_log_title[LOG_PLASMA_STORM] = "Plasma Storm!";
$l_log_text[LOG_BOUNTY_FEDBOUNTY] = "The Federation has placed a bounty on you for the amount of [amount] credits.";
$l_log_title[LOG_BOUNTY_FEDBOUNTY] = "Federation Bounty!";
$l_new_pwis = "Your password is";
$l_planet2_sector = "You are not in the same sector as that planet.";
$l_planet_destroyplanet = "Destroy Planet";
$l_planet_warning = "Doing this will totally destroy this planet";
$l_planet_confirm = "Do you really want to destroy this planet?";
$l_port_bounty = "You can not access a special port while you have a bounty on you placed by The Federation.<BR>";
$l_port_bounty2 = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "You do not have enough credtis to pay the bounty of [amount] credits.<BR>";
$l_port_bountypaid = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_port_loannotrade = "The IGB has issued a lockdown on your ship account due to a late loan payment. You cannot trade at a special port until you pay back your loan.";
$l_team_notyours = "You must be in the Alliance in order to invite someone.";
$l_team_leavefirst = "You must leave a team first before joining another.";


$l_tdr_engageagain = "Click <A HREF=\"traderoute.php?engage=[tdr_engage]\">here</A> to do this trade route again, or here to do it <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=5\">five</A> or <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=10\">ten</A> or <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=50\">fifty</A> times<p>";
$l_scan_bounty = "This ship has a total bounty on it of [amount] credits.";
$l_scan_fedbounty = "This ship has a bounty on it from The Federation.";
$l_by_nofedbounty = "Attacking this player will <B>NOT</B> result in The Federation placing a bounty on you.";

//Fig Drops

$l_sofa = "Sub-Orbital Fighter Attack";
$l_bombsaway = "You send your fighters spiralling towards the planet as you streak by at maximum range.";
$l_bigfigs = "Your huge ship has given them ample warning.  Your fighters will be less successful.";
$l_bigbeams = "There is a bright flash of discharging beams.  Your fighters probably didn't make it to the atmosphere.";
$l_bigtorps = "A large explosion blossoms in the upper air of the planet.  Your fighters probably didn't have time to attack.";
$l_strafesuccess = "It looks like some of your fighters made it through, although you can't tell how many from here.";
$l_log_text[LOG_PLANET_BOMBED] = "Your planet [planet_name] in sector [sector] was bombed by [name]. You used [beams] energy and [torps] torpedoes in your defense.  You lost [figs] fighters.";
$l_log_title[LOG_PLANET_BOMBED] = "<font color=red>Planet bombed!</font>";
$l_lssd = "Last ship seen device";
$l_lss = "Last ship seen in this sector";
$l_map = "Map";
$l_igb_errnobase = "The IGB can not transfer credits to a planet without a base.";
$l_planet_readlog_link = "View";
$l_planet_readlog = "[View] Players Log";


//Changed messages
$l_log_text[LOG_TOW] = "Your ship has been towed from sector [sector] to sector [newsector] because your average tech level exceeded the limit value of [hull].";

//Footer text
$l_footer_one_player_on = "There is 1 player online.";
$l_footer_players_on_1 = "There are";
$l_footer_players_on_2 = "players online.";
$l_footer_until_update = "seconds until next update.";

//Ship officer insignia                
$l_insignia[0] = "New Recruit";     
$l_insignia[1] = "Crewman";            
$l_insignia[2] = "Crewman First Class";
$l_insignia[3] = "Petty Officer 3rd Class";
$l_insignia[4] = "Petty Officer 2nd Class";
$l_insignia[5] = "Petty Officer 1st Class";
$l_insignia[6] = "Chief Petty Officer";
$l_insignia[7] = "Senior Chief Petty Officer";
$l_insignia[8] = "Master Chief Petty Officer";
$l_insignia[9] = "Ensign";          
$l_insignia[10] = "Lieutenant Junior Grade";
$l_insignia[11] = "Lieutenant";    
$l_insignia[12] = "Lieutenant Commander";
$l_insignia[13] = "Commander";         
$l_insignia[14] = "Captain";               
$l_insignia[15] = "Fleet Captain"; 
$l_insignia[16] = "Commodore";
$l_insignia[17] = "Rear Admiral";
$l_insignia[18] = "Vice Admiral";
$l_insignia[19] = "Admiral";           

*/

// planet.php planet2.php planet3.php

$l_planet_title		 = "Menú del Planeta"; 
$l_planet_none		 = "No estás en el mismo sector que este planeta, así que no puedes interactuar con él."; 
$l_planet_capture1	 = "capturar";  // thats the link's text
$l_planet_capture2	 = "Puedes [capture] el planeta o solo dejarlo indefenso."; 
$l_planet_unowned	 = "Este planeta no tiene propietário"; 
$l_planet_unnamed        = "Bienvenido al planeta sin nombre de [name]"; 
$l_planet_named		 = "Bienvenido a [planetname], propiedad de [name]."; 
$l_planet_onsurface	 = "Actualmente estás en la superficie del planeta."; 
$l_planet_orbit 	 = "Actualmente estás orbitando el planeta."; 
$l_planet_leave_link     = "Despegar"; 
$l_planet_leave          = "[leave] del Planeta"; 
$l_planet_name_link = "Nombre"; 
$l_planet_name2 = "[name] del Planeta"; 
$l_planet_land_link      = "Aterrizar"; 
$l_planet_land           = "[land] en el Planeta"; 
$l_planet_logout	 = "También puedes <a href=logout.php>desconectar</a> en la seguridad de tu planeta."; 
$l_planet_selling	 = "El planeta está vendiendo actualmente mercancías."; 
$l_planet_not_selling    = "El planeta no está vendiendo actualmente mercancías."; 
$l_planet_transfer_link	 = "Transferir"; 
$l_planet_transfer	 = "[transfer] mercancías/recursos/colonos de/hacia el Planeta"; 
$l_planet_hasbase	 = "Tienes una base en este planeta."; 

$l_planet_perc		 = "Porcentajes de Producción"; 
$l_planet_interest	 = "* La producción de créditos más allá de los intereses del banco son 100 - otros porcentajes"; 
$l_planet_update	 = "Actualizar"; 
$l_planet_tsell_link	 = "Vendiendo"; 
$l_planet_tsell		 = "Cambiar a planeta [selling] mercancías"; 
$l_planet_bbase_link	 = "construir una base"; 
$l_planet_bbase		 = "Con mercancías y créditos suficientes puedes [build] para ayudar a defender el planeta."; 
$l_planet_bbuild	 = "Base construída"; 
$l_planet_mcorp_linkC	 = "Planeta Corporativo"; 
$l_planet_mcorp_linkP	 = "Planeta Personal"; 
$l_planet_mcorp		 = "También puedes convertir este planeta en un [planet]"; 
$l_planet_buy_link	 = "Comprar"; 
$l_planet_buy		 = "[buy] mercancías del Planeta"; 
$l_planet_att_link	 = "Atacar"; 
$l_planet_att		 = "[attack] al Planeta"; 
$l_planet_att_sure	 = "¿Estás SEGURO...?"; 
$l_planet_scn_link	 = "Escanear"; 
$l_planet_scn		 = "[scan] Planeta"; 
$l_planet_nowsell        = "Ahora el planeta puede vender."; 
$l_planet_nownosell      = "Ahora el planeta no puede vender."; 
$l_planet_iname		 = "Introduce un nuevo nombre para el planeta"; 
$l_planet_cname		 = "El nombre del planeta ha cambiado a "; 
$l_planet_landed	 = "Has aterrizado en la superficie del planeta."; 
$l_planet_left		 = "Ya no estás en la superficie del planeta."; 
$l_planet_cinfo		 = "Tienes espacio para [cargo] unidades de carga adicional. Tienes capacidad para [energy] unidades adicionales de energía."; 
$l_planet_toplanet	 = "¿Al Planeta?"; 
$l_planet_baseinfo	 = "Para construir una base debe haber al menos $base_credits créditos, $base_ore unidades de oro, $base_organics unidades de minerales, y $base_goods undidades de bienes en el planeta."; 
$l_planet_p_under        = "No puedes cambiar los porcentajes de producción a un número negativo."; 
$l_planet_p_over	 = "No puedes cambiar los porcentajes de producción a un total mayor que el 100%."; 
$l_planet_p_changed	 = "Porcentajes de producción cambiados."; 
$l_plant_scn_turn	 = "Necesitas al menos un turno para escanear un planeta."; 
$l_planet_noscan	 = "¡Los sensores no pueden fijar el objetivo!"; 
$l_planet_logscanA	 = "[name] ha intentado escanear uno de tus planetas en el sector [sector], pero ha fallado."; 
$l_planet_logscanB	 = "Uno de tus planetas en el sector [sector] ha sido escaneado por [name]."; 
$l_planet_scn_report	 = "Resultados del escaneo a [name], propiedad de [owner]"; 
$l_base	  		 = "Base"; 
$l_planet_ison		 = "está en el planeta"; 
$l_planet_captured	 = "Planeta capturado"; 
$l_planet_notdef	 = "¡El planeta no ha sido vencido!"; 
$l_planet_caplog	 = "Tu planeta '[planetname]' en el sector [sector] ha sido capturado por [name]."; 
$l_planet_noone = "nadie"; 

$l_planet2_title	 = "Transferencia Planetaria"; 
$l_planet2_noturn	 = "Necesitas al menos un turno para realizar una transferencia planetaria."; 
$l_planet2_noten 	 = "No tienes suficiente "; 
$l_planet2_fortr	 = "para la transferencia solicitada."; 
$l_planet2_settr	 = "Estableciendo la cantidad de la transferencia a "; 
$l_planet2_losup	 = "El planeta solo ha sido capaz de ofrecer "; 
$l_planet2_notowner	 = "No eres el propietario de este planeta."; 
$l_planet2_compl	 = "Transferencia completada."; 
$l_planet2_power	 = "capacidad de energía"; 
$l_planet2_comp 	 = "capacidad de computadora"; 
$l_planet2_laun 	 = "capacidad de lanzadora"; 
$l_planet2_nocorptransfer = "No puedes transferir créditos desde o hacia planetas corporativos."; 
$l_planet2_baseexceeded = "Los planetas sin una base no puede contener esa cantidad de créditos."; 

$l_planet3_title	 = "Comerciando en el Planeta"; 

// planet-report.php

$l_pr_title		 = "Informe del Planeta"; 
$l_pr_teamlink		 = "Mostrar planetas de la Alianza"; 
$l_pr_noplanet		 = "No tienes tantos planetas"; 
$l_pr_clicktosort	 = "Pulsa en un título de columna para ordenarlo"; 
$l_pr_totals		 = "Totales"; 

// rsmove.php
$l_rs_title 		= "Movimiento EspacioReal"; 
$l_rs_whichsector       = "¿Qué sector quieres alcanzar a través de EspacioReal?"; 
$l_rs_insector		= "Actualmente estás en el sector [sector] - y hay sectores disponibles de 0 a [sector_max]."; 
$l_rs_submit		= "Computar"; 
$l_rs_movetime		= "Con tus motores te llevará [triptime] turnos completar el viaje."; 
$l_rs_energy		= "Conseguirás [energy] unidades de energía"; 
$l_rs_noturns		= "No tienes suficientes turnos, y no puedes embarcarte en este viaje."; 
$l_rs_engage_link	= "Iniciar"; 
$l_rs_engage		= "Tienes [turns] turnos. ¿[engage] motores?"; 

$l_rs_invalid		= "Destino no válido"; 
$l_rs_ready 		= "Estas en el sector [sector]. Has usado [triptime] turnos, y has conseguido [energy] unidades de energía."; 

// navcomp.php	

$l_nav_title		 = "Computadora de Navegación"; 
$l_nav_nocomp		 = "La computadora de navegación no está disponible"; 
$l_nav_query		 = "Introduce el sector hacia el que deseas encontrar una ruta: "; 
$l_nav_pathfnd		 = "Ruta encontrada"; 
$l_nav_answ1		 = "Te costará"; 
$l_nav_answ2		 = "turnos llegar a ese sector."; 
$l_nav_proper		 = "La tecnología de tu computadora es demasiado primitiva para calcular la ruta de salto a esa distancia."; 


// attack.php

$l_att_title		 = "Atacar Nave"; 
$l_att_notarg		 = "El objetivo no está en este sector."; 
$l_att_noturn		 = "Necesitas al menos un turno para atacar."; 
$l_att_noatt		 = "No está permitido atacar a alguien en este sector."; 
$l_att_flee		 = "¡El objetivo te ha esquivado!"; 
$l_att_ewd		 = "¡El objetivo a iniciado un dispositivo de salto de emergencia cuando ha sido atacado!"; 
$l_att_att		 = "Ataques"; 
$l_att_beams		 = "Daño de los lásers:"; 
$l_att_torps		 = "Daño de los torpedos:"; 
$l_att_fighters		 = "Ataque de los cazas"; 
$l_att_lost		 = "perdido"; 
$l_att_ylost		 = "Has perdido"; 
$l_att_sdown		 = " ha perdido sus escudos !"; 
$l_att_ydown		 = "¡Has perdido tus escudos!"; 
$l_att_shits		 = " ha recibido un ataque en sus escudos por"; 
$l_att_yhits		 = "Tus escudos han sido atacados por"; 
$l_att_dmg		 = "daño"; 
$l_att_sarm		 = " tiene una brecha en su armadura!"; 
$l_att_yarm		 = "¡Tienes una brecha en tu armadura!"; 
$l_att_ashit		 = " ha recibido un ataque en su armadura por"; 
$l_att_ayhit		 = "Has recibido un ataque en tu armadura por"; 
$l_att_lostf		 = "perdió todos sus cazas."; 
$l_att_ylostf		 = "Has perdido todos tus cazas."; 
$l_att_sdest		 = " contempla como su nave es destruida."; 
$l_att_espod		 = "¡Ha sido lanzada una cápsula de salvamento!"; 
$l_att_ysalv		 = "Has capturado [salv_ore] unidades de minerales, [salv_organics] unidades de orgánicos, [salv_goods] unidades de bienes, y has capturado el [ship_salvage_rate]% de la nave por [ship_salvage] créditos.<br>Tu puntuación ha cambiado en [rating_change] puntos."; 

$l_att_andused		 = "y has usado"; 
$l_att_stilship		 = "No has destruido la nave de [name]."; 
$l_att_atyou		 = "te ha atacado"; 
$l_att_and		 = "y"; 
$l_att_yshiplost	 = "¡Tu nave ha sido destruida!"; 
$l_att_salv		 = "[name] ha capturado [salv_ore] unidades de minerales, [salv_organics] unidades de orgánicos, [salv_goods] unidades de bienes, y ha capturado el [ship_salvage_rate]% de la nave por [ship_salvage] créditos."; 

// warpedit 1-3.php


$l_warp_title		 = "Usar Editor de Saltos"; 
$l_warp_turn		 = "Necesitas al menos un turno para usar el editor de saltos."; 
$l_warp_none		 = "No tienes ningún editor de saltos."; 
$l_warp_forbid		 = "No está permitido usar un Editor de Saltos en este sector."; 
$l_warp_nolink		 = "No hay enlaces hacia fuera de este sector."; 
$l_warp_linkto		 = "Los enlaces llevan de este sector hacia"; 
$l_warp_query		 = "¿Hacia qué sector te gustaría crear un enlace?"; 
$l_warp_oneway		 = "¿De una dirección?"; 
$l_warp_dest		 = "Alternativamente, puedes destruir un enlace hacia un sector."; 
$l_warp_destquery	 = "¿Hacia qué sector quieres quitar el enlace?"; 
$l_warp_bothway		 = "Ambas direcciones"; 
$l_warp_nosector	 = "El sector no existe."; 
$l_warp_twoerror	 = "No está permitido usar un Editor de Saltos para crear un enlace de ambas direcciones en el sector [target_sector]."; 
$l_warp_sectex		 = "No se puede crear un enlace de salto desde el sector actual - habrás excedido el máximo de $link_max por sector."; 
$l_warp_linked		 = "El sector de destino ([target_sector]) ya tiene un enlace desde este sector."; 
$l_warp_unlinked	 = "El enlace de destino ([target_sector]) no tiene un enlace desde este sector."; 
$l_warp_coneway	         = "Se ha creado un enlace de una dirección hacia"; 
$l_warp_ctwoway		 = "Se ha creado un enlace desde y hacia"; 
$l_warp_forbidtwo	 = "No está permitido usar un Editor de Saltos para quitar un enlace de dos direcciones hacia el sector [target_sector]."; 
$l_warp_removed		 = "Enlace quitado hacia"; 
$l_warp_removedtwo	 = "Enlace quitado desde y hacia"; 

// genesis.php

$l_gns_title		 = "Usar Dispositivo Génesis"; 
$l_gns_turn		 = "Necesitas al menos un turno para usar un dispositivo génesis."; 
$l_gns_onplanet		 = "No puedes usar este dispostivo mientras estás en la superficie del planeta."; 
$l_gns_full		 = "Este sistema solar ya está lleno."; 
$l_gns_planetex		 = "Ya hay un planeta en este sector."; 
$l_gns_nogenesis	 = "No tienes ningún dispositivo génesis."; 
$l_gns_forbid		 = "No está permitido crear un planeta en este sector."; 
$l_gns_bforbid		 = "Las bases que hay en este sector estan interfiriendo con tu dispositivo génesis. La creación del planeta no es posible."; 
$l_gns_pcreate		 = "Planeta creado."; 

// ship.php

$l_ship_title		 = "Órdenes de la Nave"; 
$l_ship_the		 = "La"; 
$l_ship_nolonger	 = "ya no está en este sector"; 
$l_ship_youc		 = "Ves la"; 
$l_ship_owned		 = "propiedad de"; 
$l_ship_perform		 = "Puedes realizar las siguientes acciones:"; 

// selfdestruct.php

$l_die_title		 = "Autodestrucción"; 
$l_die_rusure		 = "¿Estás seguro de que deseas destruir tu nave? Esto te eliminará del juego."; 
$l_die_goodbye		 = "¡Adios, galaxia cruel!"; 
$l_die_check		 = "¿Estás seguro de que deseas eliminarte del juego?"; 
$l_die_nonono		 = "¡NO! ¡NO! ¡NO!"; 
$l_die_what		 = "¿En qué estaba yo pensando?"; 
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. ¡Bum!"; 
$l_die_vapor		 = "Tu nave y todos los que estaban a bordo han sido vaporizados."; 
$l_die_please		 = "Por favor, <A HREF=logout.php>desconéctate</A>"; 
$l_die_exploit		 = "No juegues con lo que no entiendes."; 

// move.php

$l_move_title 		 = "Mover"; 
$l_move_turn		 = "Necesitas al menos un turno para moverte."; 
$l_move_failed		 = "¡Movimiento fallido!"; 

// scan.php

$l_scan_title		 = "Escanear Nave"; 
$l_scan_turn		 = "Necesitas al menos un turno para escanear la nave de otro."; 
$l_scan_ron		 = "Los resultados del escaneo de "; 
$l_scan_capt		 = "Capitaneada por:"; 
$l_scan_arma		 = "Armamento:"; 
$l_scan_carry		 = "Transportando:"; 

// lrscan.php

$l_lrs_title		 = "Escaneo de Largo Alcance"; 
$l_lrs_nofull		 = "Tus escáners no poseen la capacidad de realizar escaneos de largo alcance."; 
$l_lrs_noturns		 = "Necesitas al menos $fullscan_cost turno(s) para realizar un escaneo de largo alcance."; 
$l_lrs_used		 = "Usado"; 
$l_lrs_turns		 = "turno(s)"; 
$l_lrs_left		 = "restantes"; 
$l_lrs_reach		 = "Las siguientes localizaciones pueden ser alcanzadas desde el sector [sector]:"; 
$l_lrs_links		 = "Enlaces"; 
$l_lrs_ships		 = "Naves"; 
$l_lrs_click		 = "Pulsa en los enlaces para moverte hacia ese sector."; 
$l_lrs_cantscan		 = "¡No puede escanear el sector desde el sector actual!"; 
$l_lrs_zero		 = "¡El sector 0 está demasiado abarrotado para escanear por naves!"; 
$l_lrs_moveto		 = "para mover hacia el sector"; 
$l_log_titlet = "Ver Diario"; 

// log.php

$l_log_months = array('Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre');
$l_log_months_short = array('Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic');
$l_log_pod = "¡Afortunadamente tenías una cápsula de salvamento!"; 
$l_log_nopod = "<font color=yellow><b>No tenías cápsula de salvamento. Has muerto.</b></font>"; 
$l_log_log = "Diario de [player]"; 
$l_log_start = "Entrada en el diario para"; 
$l_log_end = "Fin de la entrada de diario para"; 
$l_log_click = "Pulsa <A HREF=main.php><font color=#00ff00>aquí</font></A> para volver al menú principal."; 
$l_log_note = "NOTA: Si esta página se muestra incorrectamente, o si simplemente no te gustan los efectos de html dinámico, o lo encuentras molesto, puedes desactivarlos <a href=options.php><font color=#00FF00>aquí</font></a>"; 

$l_log_text[LOG_LOGIN] = "Te has conectado, desde [ip]."; 
$l_log_title[LOG_LOGIN] = "Conectado"; 
$l_log_text[LOG_LOGOUT] = "Te has desconectado, desde [ip]."; 
$l_log_title[LOG_LOGOUT] = "Desconectado"; 
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] fue avistado en un vector de ataque, pero tus grandes habilidades como piloto y tus buenos motores te permitieron esquivar al enemigo."; 
$l_log_title[LOG_ATTACK_OUTMAN] = "¡Acción evasiva!"; 
$l_log_text[LOG_ATTACK_OUTSCAN] = "Has detectado cómo las armas de [player] intentaban fijarte como objetivo, pero tus generadores de ocultación consiguieron engañar los primitivos sensores del enemigo."; 
$l_log_title[LOG_ATTACK_OUTSCAN] = "¡Ocultación exitosa!"; 
$l_log_text[LOG_ATTACK_EWD] = "Eres sorprendido por el traicionero ataque de [player]. Puedes ver cómo los misiles se dirigen hacia ti mientras frenéticamente pulsas el botón para el salto de emergencia. El mundo se desvanece alrededor y, por un milisegundo, crees que estás muerto. Cuando finalmente abres los ojos puedes ver que has sido seguramente transportado a otro lugar. Pero dónde exactamente, no lo sabes..."; 
$l_log_title[LOG_ATTACK_EWD] = "¡Salto de Emergencia!"; 
$l_log_text[LOG_ATTACK_EWDFAIL] = "Tus sensores detectan la nave de [player] en un vector de ataque. \"Mejor estar seguro que lamentarlo\", piensas, pulsando el botón del salto de emergencia. Oyes un extraño sonido de choque que proviene de la sala de motores y hueles a circuitería quemada. \"¡Estúpido trozo de chatarra!\", gritas, pateando a la computadora. La computadora emite unos bips de protesta mientras te preparas para la batalla que se avecina..."; 
$l_log_title[LOG_ATTACK_EWDFAIL] = "¡Salto de emergencia <font color=red>fallido!</font>!"; 
$l_log_text[LOG_ATTACK_LOSE] = "Tu nave ha sido atacada por [player]. Por mucho que lo intentas no puedes defenderte contra el superior armamento de [player]. Tu nave ha sido destruida. "; 
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>¡Combate perdido!</font>"; 
$l_log_text[LOG_ATTACKED_WIN] = "Tu nave ha sido atacada por [player]. Batallas un poco, luego la pelea se acaba. Pierdes [armor] puntos de armadura y [fighters] cazas en la escaramuza."; 
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>¡Escaramuza!</font>"; 
$l_log_text[LOG_TOLL_PAID] = "Debes pagar [toll] créditos para entrar en el sector [sector]. Te prometes a ti mismo que encontrarás un modo de que te devuelvan el dinero."; 
$l_log_title[LOG_TOLL_PAID] = "Extorsión"; 
$l_log_text[LOG_HIT_MINES] = "Golpeas [mines] minas mientras navegas en el sector [sector]."; 
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>¡Alerta de minas!</font>"; 
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Tu nave ha sido destruida por un campo de minas en el sector [sector]."; 
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=yellow>¡Alerta de minas!</font>"; 
$l_log_text[LOG_PLANET_DEFEATED_D] = "Tu planeta [planet_name] en el sector [sector] ha sido capturado durante una batalla contra [name]. Afortunadamente, la fuerte lealtad de tus ciudadanos ha jugado a tu favor. Valientemente han elegido destruir el planeta antes que tener que caer en manos enemigas. Organizas impresionantes funerales en memoria de tu fervorosa gente."; 
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planeta destruido</font>"; 
$l_log_text[LOG_PLANET_DEFEATED] = "Tu planeta [planet_name] en el sector [sector] ha sido capturado durante una batalla contra el despreciable [name]. La gente de tu planeta dan la bienvenida al nuevo gobernante. Escuchas un testimonio en la BNN: \"¡Nos alegramos de habernos desecho de ese patético comeyogures! ¡No queremos a un apestoso perdedor que no sepa protegernos!\". Juras que les harás pagar su arrogancia."; 
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>¡Planeta capturado!</font>"; 
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Tu planeta [planet_name] en el sector [sector] ha sido atacado por [name]. De todos modos los ciudadanos han organizado una valiente defensa y han conseguido destruir al oponente. Han capturado algunos recursos de los restos de la nave destruida: [goods] bienes, [ore] minerales, [organics] orgánicos y el [salvage]% de los bienes de la nave por [credits] créditos."; 
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "¡Victoria!"; 
$l_log_title[LOG_RAW] = "Noticia"; 
$l_log_text[LOG_TOLL_RECV] = "Los cazas en el sector [sector] han recogido un 'impuesto' de [toll] créditos."; 
$l_log_title[LOG_TOLL_RECV] = "Ingresos de peaje"; 
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] han sido destruidos en el sector [sector]."; 
$l_log_title[LOG_DEFS_DESTROYED] = "Defensas de sector destruidas"; 
$l_log_text[LOG_PLANET_EJECT] = "Has sido expulsado del planeta en el sector [sector] porque [name] dejó la alianza."; 
$l_log_title[LOG_PLANET_EJECT] = "¡Expulsado!"; 
$l_log_text[LOG_BADLOGIN] = "Ha habido un intento de conexión erróneo desde [ip]."; 
$l_log_title[LOG_BADLOGIN] = "Conexión errónea"; 
$l_log_text[LOG_PLANET_SCAN] = "[name] ha escaneado tu planeta [planet_name] en el sector [sector]."; 
$l_log_title[LOG_PLANET_SCAN] = "Planeta escaneado"; 
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] ha intentado escanear tu planeta [planet_name] en el sector [sector], pero ha fallado."; 
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Escaneo de planeta fallido"; 
$l_log_text[LOG_SHIP_SCAN] = "[player] ha escaneado tu nave."; 
$l_log_title[LOG_SHIP_SCAN] = "Nave escaneada"; 
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] ha intentado escanear tu nave, pero ha fallado."; 
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Escaneo de nave fallido"; 
$l_log_text[LOG_FURANGEE_ATTACK] = "Atacando a [player]..."; 
$l_log_title[LOG_FURANGEE_ATTACK] = "Ataque"; 
$l_log_text[LOG_STARVATION] = "¡Uno de tus planetas en [sector] no puede sostener a su población! Se necesitan más orgánicos. [starvation] colonos han muerto de hambre."; 
$l_log_title[LOG_STARVATION] = "<font color=yellow>¡Hambruna!</font>"; 
$l_log_title[LOG_TOW] = "¡Remolcado!"; 
$l_log_text[LOG_DEFS_DESTROYED_F] = "Has destruido [fighters] cazas patrulla en el sector [sector]."; 
$l_log_title[LOG_DEFS_DESTROYED_F] = "Cazas destruidos"; 
$l_log_text[LOG_DEFS_KABOOM] = "Has sido destruido por un grupo de cazas en el sector [sector]. "; 
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>¡Nave destruida!</font>"; 
$l_log_text[LOG_HARAKIRI] = "Estabas cansado de capitanear esa canoa espacial, así que decidiste que el universo estaría mejor sin ella. Autorizado por [ip]."; 
$l_log_title[LOG_HARAKIRI] = "<font color=red>¡Autodestruido!</font>"; 
$l_log_text[LOG_TEAM_REJECT] = "[player] ha rechazado una invitación de unirse a tu alianza, [teamname]."; 
$l_log_title[LOG_TEAM_REJECT] = "Invitación rechazada"; 
$l_log_text[LOG_TEAM_RENAME] = "Has renombrado tu alianza a [team]."; 
$l_log_title[LOG_TEAM_RENAME] = "Alianza renombrada"; 
$l_log_text[LOG_TEAM_M_RENAME] = "El coordinador de tu alianza la ha renombrado a [team]."; 
$l_log_title[LOG_TEAM_M_RENAME] = "Alianza renombrada"; 
$l_log_text[LOG_TEAM_KICK] = "Has sido expulsado de la alianza [team]."; 
$l_log_title[LOG_TEAM_KICK] = "¡Expulsado de la alianza!"; 
$l_log_text[LOG_TEAM_CREATE] = "Has creado una nueva alianza, [team]."; 
$l_log_title[LOG_TEAM_CREATE] = "Nueva alianza creada"; 
$l_log_text[LOG_TEAM_LEAVE] = "Has dejado la alianza [team]."; 
$l_log_title[LOG_TEAM_LEAVE] = "Alianza abandonada"; 
$l_log_text[LOG_TEAM_NEWLEAD] = "Has dejado la alianza [team]. Has relegado el liderazgo de la alianza a [name]."; 
$l_log_title[LOG_TEAM_NEWLEAD] = "Alianza abandonada"; 
$l_log_text[LOG_TEAM_LEAD] = "El coordinador de tu alianza ha decidido abandonar [team]. Has sido desgnado como nuevo líder."; 
$l_log_title[LOG_TEAM_LEAD] = "¡Promoción!"; 
$l_log_text[LOG_TEAM_JOIN] = "Te has unido a la alianza [team]."; 
$l_log_title[LOG_TEAM_JOIN] = "Unido a alianza"; 
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] ha aceptado unirse a [team]. Esto te lleva un paso más allá hacia la dominación galáctica."; 
$l_log_title[LOG_TEAM_NEWMEMBER] = "Nuevo miembro de la alianza"; 
$l_log_text[LOG_TEAM_INVITE] = "Has sido invitado a formar parte de [team]."; 
$l_log_title[LOG_TEAM_INVITE] = "Invitación"; 
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] ha abandonado tu alianza."; 
$l_log_title[LOG_TEAM_NOT_LEAVE] = "La alianza pierde a un miembro"; 
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] se ha autodestruido desde la ip [ip]."; 
$l_log_title[LOG_ADMIN_HARAKIRI] = "Autodestruido"; 
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] tenía [quantity] [type], con un máximo de contenedores de [holds]"; 
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Valor ilegal de la nave"; 
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] ha intentado capturar el planeta de [defender]  en el sector [sector]. En vez de eso el planeta ha sido destruido."; 
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planeta destruido"; 
$l_log_text[LOG_DEFENCE_DEGRADE] = "Los cazas de la defensa de sector [sector] se han degradado un [degrade] por ciento debido a falta de energía."; 
$l_log_test[LOG_DEFENCE_DEGRADE] = "Defensas de sector degradadas"; 
$l_log_text[LOG_PLANET_CAPTURED] = "Has capturado un planeta que pertenece a [owner]. Tenía [cols] colonos y [credits] créditos en él."; 
$l_log_title[LOG_PLANET_CAPTURED] = "¡Planeta capturado!"; 

// modify-defences.php

$l_md_title		 = "Defensas de Sector"; 
$l_md_invalid		 = "Defensas de Sector no válidas"; 
$l_md_nolonger		 = "Las Defensas de Sector seleccionadas ya no están ahí."; 
$l_md_you		 = "tú mismo"; 
$l_md_bmines		 = "Tus lásers han destruido"; 
$l_md_msgdownerb	 = "[name] ha destruido [mines] minas en el sector [sector]."; 
$l_md_retr		 = "Te han sido devueltos"; 
$l_md_mode		 = "Los cazas seleccionados han sido modificados a modo [mode]."; 
$l_md_consist		 = "Las defensas de este sector consisten en [qty] [type] propiedad de [owner]."; 
$l_md_youcan		 = "Puedes"; 
$l_md_retrieve		 = "Devolver"; 
$l_md_change		 = "Cambiar la configuración de los cazas"; 
$l_md_cmode		 = "Modo de los cazas"; 
$l_md_attack		 = "Atacar"; 
$l_md_toll		 = "Peaje"; 
$l_md_attdef		 = "Ataca las Defensas de Sector. Todos los cazas del sector tomarán represalias."; 
$l_md_noturn	  	 = "Necesitas al menos un turno."; 
$l_md_nothere            = "Necesitas estar en el mismo sector que las Defensas de Sector."; 
$l_md_notyours           = "Acción no permitida. Esas Defensas de Sector no te pertenecen."; 
$l_md_yours              = "No puedes atacar tus propias Defensas de Sector."; 

// news.php


$l_news_title		 = "BlackNova Universe News (Noticias del Unverso BlackNova)"; 
$l_news_info		 = "BNN está entre los líderes de la galaxia<br>en la comunicación de noticias e información.<br>¡Una plantilla activa las 24 horas, los siete días de la semana,<br>ubicada en la sede central galáctica de BNN<br>situada en Alfa Centauri y con agencias en toda la galaxia!"; 
$l_news_for		 = "Noticias para"; 
$l_news_prev		 = "día anterior"; 
$l_news_next		 = "día siguiente"; 
$l_news_none		 = "Lo sentimos, no hay noticias hoy."; 
$l_news_flash		 = "Avance Informativo"; 

// dump.php
$l_dump_title		 = "Dejando colonos"; 
$l_dump_turn		 = "Necesitas al menos un turno para dejar colonos."; 
$l_dump_nocol		 = "No tienes colonos en tu nave para realizar la acción."; 
$l_dump_dumped		 = "Los colonos han sido dejandos en el almacén de provisiones."; 
$l_dump_nono		 = "Necesitas al menos un almacén de provisiones para hacer esto."; 

// readmail.php
$l_readm_title		 = "Leer Mensaje"; 
$l_readm_delete		 = "MENSAJE BORRADO"; 
$l_readm_nomessage	 = "No hay mensajes esperándote...<br>"; 
$l_readm_center		 = "Centro de Recepción de Mensajes"; 
$l_readm_sender		 = "Remitente del Mensaje"; 
$l_readm_captn		 = "Capitán de la"; 
$l_readm_del		 = "Borrar"; 
$l_readm_repl		 = "Responder"; 

// mailto2.php

$l_sendm_title		 = "Enviar Mensaje"; 
$l_sendm_to		 = "Para"; 
$l_sendm_from		 = "De"; 
$l_sendm_ally		 = "Alianza:"; 
$l_sendm_subj		 = "Asunto"; 
$l_sendm_mess		 = "Mensaje"; 
$l_sendm_send		 = "Enviar"; 
$l_sendm_sent		 = "Mensake enviado"; 

// zoneinfo.php

$l_zi_title		 = "Información de la Zona"; 
$l_zi_nexist		 = "¡Esta sección de espacio no existe!"; 
$l_zi_feds		 = "Federación"; 
$l_zi_traders		 = "La Coalición de Comercio Libre"; 
$l_zi_nobody		 = "Nadie"; 
$l_zi_war		 = "Espacio en concurso"; 
$l_zi_allow		 = "Permitido"; 
$l_zi_notallow		 = "No permitido"; 
$l_zi_limit		 = "Limitado al propietario y aliados"; 
$l_zi_ul		 = "ilimitado"; 
$l_zi_control		 = "Tienes el control de esta zona"; 
$l_zi_tochange		 = "para cambiar sus leyes."; 
$l_zi_owner		 = "Propietario de la zona"; 
$l_zi_maxhull		 = "Máximo promedio de nivel tecnológico permitido"; 

// zoneedit.php

$l_ze_title		 = "Editar Zona"; 
$l_ze_notowner		 = "No eres el propietario de esta zona, así que no puedes editarla."; 
$l_ze_name		 = "Nombre de la zona"; 
$l_ze_allow		 = "Permitir"; 
$l_ze_attacks		 = "Permitir atacar a otras naves"; 
$l_ze_genesis		 = "Permitir crear nuevos planetas"; 
$l_ze_return		 = "para volver a a página de información de la zona"; 
$l_ze_saved		 = "Tus cambios han sido guardados."; 

// teams.php

$l_team_title		 = "Alianzas"; 
$l_team_menu		 = "para regresar al Menú de Alianzas"; 
$l_team_galax		 = "Alianzas presentes en la Galaxia:"; 
$l_team_members		 = "Miembros"; 
$l_team_coord		 = "Coordinador"; 
$l_team_member		 = "Miembro"; 
$l_team_noinvite	 = "Nadie te ha invitado a unirte a una alianza."; 
$l_team_ifyouwant	 = "Si quieres unirte a una alianza, envía un mensaje a su coordinador pidiendo ser invitado."; 
$l_team_tocreate	 = "para crear una nueva alianza."; 
$l_team_injoin		 = "Te han invitado a unirte"; 
$l_team_tojoin		 = "para unirte"; 
$l_team_or		 = "o"; 
$l_team_reject		 = "para rechazar la invitación."; 
$l_team_ed		 = "Editar"; 
$l_team_inv		 = "Invitar"; 
$l_team_leave		 = "Abandonar"; 
$l_team_eject		 = "Expulsar"; 
$l_team_pending		 = "Invitación pendiente para"; 
$l_team_noinvites	 = "Nadie ha sido invitado para formar parte de"; 
$l_team_confirmleave	 = "¿Estás seguro de querer abandonar "; 
$l_team_onlymember	 = "Eras el único miembro, así que [team_name] ya no existe."; 
$l_team_youarecoord	 = "Eres el coordinador de"; 
$l_team_relinq		 = "Debes relegar tu papel a otro jugador."; 
$l_team_newc		 = "Nuevo coordinador:"; 
$l_team_youveleft	 = "Has dejado la alianza"; 
$l_team_relto		 = "relegando las funciones de coordinador a"; 
$l_team_welcome		 = "Bienvenido a la alianza"; 
$l_team_noinviteto	 = "No has sido invitado en ese equipo."; 
$l_team_ejectsure	 = "Estás seguro de que deseas expulsar a"; 
$l_team_ejected 	 = "ha sido expulsado de la alianza!"; 
$l_team_testing		 = "Probando fase..."; 
$l_team_pw		 = "Contraseña"; 
$l_team_entername	 = "Introduce el nombre de la Alianza"; 
$l_team_enterdesc	 = "Introduce una descripción de la Alianza"; 
$l_team_hcreated	 = "ha sido creada y tú eres su líder"; 
$l_team_alliance	 = "Alianza"; 
$l_team_selectp		 = "Elije el Jugador al que deseas invitar"; 
$l_team_isorry		 = "Lo lamento, pero [name] ya ha sido invitado a formar parte de una alianza - solo una invitación puede estar activa en cualquier momento"; 
$l_team_plinvted	 = "Jugador invitado.<br>Debes esperar a que el jugador lea tu invitación."; 
$l_team_refuse		 = "Has rechazado la invitación para unirte a"; 
$l_team_edname		 = "Editar el nombre de tu Alianza"; 
$l_team_eddesc		 = "Editar la descripción de tu Alianza"; 
$l_team_hasbeenr	 = "ha sido renombrada."; 
$l_team_error		 = "<b><font color=red>Ha ocurrido un error</font></b><br>No eres el líder de esta Alianza."; 
$l_team_notmember	 = "No eres miembro de ninguna alianza."; 
$l_team_urejected	 = "<b>ATENCIÓN</b> - has sido expulsado de"; 
$l_team_noalliances	 = "No hay alianzas en la Galaxia en este momento."; 

// ranking.php

$l_ranks_title		 = "Mejores $max_rank Jugadores"; 
$l_ranks_none		 = "No hay resultados a mostrar."; 
$l_ranks_pnum		 = "Número total de jugadores"; 
$l_ranks_dships		 = "Los jugadores con naves destruidas no son contados."; 
$l_ranks_rank		 = "Posic."; 
$l_ranks_lastlog	 = "Última conexión"; 
$l_ranks_good		 = "Bueno"; 
$l_ranks_evil		 = "Malvado"; 

// beacon.php

$l_beacon_title		 = "Lanzar Aerofaro Espacial"; 
$l_beacon_notpermitted	 = "No está permitido lanzar aerofaros espaciales en este sector."; 
$l_beacon_reads		 = "En el aerofaro actual se puede leer"; 
$l_beacon_none		 = "Actualmente no hay ningún aerofaro en este sector."; 
$l_beacon_enter		 = "Introduce el texto para el aerofaro"; 
$l_beacon_nowreads	 = "En el aerofaro ahora puede leerse"; 
$l_beacon_donthave	 = "No tienes aerofaros espaciales."; 

// emerwarp.php

$l_ewd_title		 = "Usar Dispositivo de Salto de Emergencia"; 
$l_ewd_used		 = "Dispositivo de salto de emergencía accionado - has llegado al sector [sector]."; 
$l_ewd_none		 = "No tienes un dispositivo de salto de emergencia."; 

// defence-report.php

$l_sdf_title		 = "Informe de la Defensa de Sector"; 
$l_sdf_none		 = "No has instalado Defensas de Sector."; 
$l_sdf_type		 = "Tipo"; 
$l_sdf_mode		 = "Modo"; 

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_within		 = " en "; 
$l_tdr_title    	 = "rutas comerciales"; 
$l_tdr_newtdr   	 = "Pulsa <a href=\"traderoute.php?command=new\">aquí</a> para crear una nueva ruta"; 
$l_tdr_modtdrset         = "Para modificar la configuración global de tus rutas comerciales, pulsa <a href=\"traderoute.php?command=settings\">aquí</a>";
$l_tdr_confdel  	 = "Pulsa <a href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">aquí</a> para confirmar la eliminación de la siguiente ruta comercial:";
$l_tdr_noactive 	 = "No tienes ninguna ruta comercial activa para mostrar."; 
$l_tdr_curtdr   	 = "rutas comerciales Actuales"; 
$l_tdr_deltdr   	 = "Eliminar ruta comercial"; 
$l_tdr_src      	 = "Origen"; 
$l_tdr_srctype  	 = "Tipo (orig)"; 
$l_tdr_dest     	 = "Destino"; 
$l_tdr_desttype 	 = "Tipo (dest)"; 
$l_tdr_move     	 = "Movimiento"; 
$l_tdr_circuit  	 = "Circuito"; 
$l_tdr_change   	 = "Cambiar"; 
$l_tdr_portin   	 = "Puerto en"; 
$l_tdr_planet   	 = "Planeta"; 
$l_tdr_nonexistance      = "¡El planeta no existe!"; 
$l_tdr_na       	 = "N/A"; 
$l_tdr_cargo    	 = "Carga"; 
$l_tdr_none     	 = "Ninguno"; 
$l_tdr_colonists         = "Colonos"; 
$l_tdr_fighters 	 = "Cazas"; 
$l_tdr_torps    	 = "Torpedos"; 
$l_tdr_escooped 	 = "[tdr_dist_triptime] turnos<br>[tdr_dist_scooped] energía conseguida"; 
$l_tdr_warp     	 = "Salto"; 
$l_tdr_turns    	 = "turnos"; 
$l_tdr_way      	 = "dirección"; 
$l_tdr_ways     	 = "direcciones"; 
$l_tdr_edit     	 = "Editar"; 
$l_tdr_del      	 = "Eliminar"; 
$l_tdr_nowlink1 	 = "No hay un salto de enlace desde el sector [tdr_src_sector_id] hasta el sector [tdr_dest_sector_id]"; 
$l_tdr_nowlink2 	 = "No hay un salto de enlace desde el sector [tdr_dest_sector_id] hasta el sector [tdr_src_sector_id]"; 
$l_tdr_sportissrc        = "Si un puerto especial es el destino, un planeta debe ser el destino para la colonización."; 
$l_tdr_notownplanet      = "No puedes colonizar un planeta que tú o tu equipo no posea."; 
$l_tdr_planetisdest      = "Un planeta puede ser un destino solo si el origen es un puerto especial."; 
$l_tdr_samecom 		 = "No puedes crear una ruta comercial para puertos que venden las mismas mercancías."; 
$l_tdr_sportcom 	 = "No puedes vender mercancías desde un planeta a un puerto especial."; 
$l_tdr_editerr  	 = "Error al editar: la ruta comercial no se ha encontrado en la BD"; 
$l_tdr_maxtdr   	 = "Lo lamento, pero has alcanzado el máximo número de rutas comerciales permitidas."; 
$l_tdr_createnew         = "Creando una nueva "; 
$l_tdr_editinga 	 = "Editando una"; 
$l_tdr_traderoute        = "ruta comercial"; 
$l_tdr_unnamed  	 = "Sin nombre"; 
$l_tdr_cursector         = "Actualmente estás en el sector"; 
$l_tdr_selspoint         = "Por favor, selecciona el punto de origen:"; 
$l_tdr_port     	 = "Puerto"; 
$l_tdr_insector 	 = "en el sector"; 
$l_tdr_selendpoint       = "Por favor, selecciona un punto de destino"; 
$l_tdr_selmovetype       = "Por favor, selecciona un tipo de movimiento"; 
$l_tdr_realspace         = "EspacioReal (RS)"; 
$l_tdr_selcircuit        = "Por favor, selecciona un circuito"; 
$l_tdr_oneway   	 = "Una dirección"; 
$l_tdr_errnotvalidport   = "Error: el puerto de origen [tdr_port_id] no parece ser válido."; 
$l_tdr_bothways 	 = "Ambas direcciones"; 
$l_tdr_create   	 = "Crear"; 
$l_tdr_modify   	 = "Modificar"; 
$l_tdr_returnmenu        = "Pulsa <a href=traderoute.php>aquí</a> para volver al menú de rutas comerciales."; 
$l_tdr_errnotvalidport   = "Error: el puerto de origen [tdr_port_id] no parece ser un puerto válido."; 
$l_tdr_errnoport         = "Error: no hay puertos en el sector [tdr_port_id]"; 
$l_tdr_errnosrc    	 = "Error: el planeta de origen especificado no existe."; 
$l_tdr_errnotownnotsell  = "Error: no eres el propietario del planeta [tdr_source_name] en el sector [tdr_source_sector_id] y el planeta no está vendiendo."; 
$l_tdr_errnotvaliddestport= "Error : el puerto de destino [tdr_port_id] no es un puerto válido."; 
$l_tdr_errnoport2        = "Error: no hay puertos en el sector [tdr_port_id]."; 
$l_tdr_errnodestplanet   = "Error: el planeta de destino especificado no existe."; 
$l_tdr_errnotownnotsell2 = "Error: no eres el propietario del planeta [tdr_dest_name] en el sector [tdr_dest_sector_id] y el planeta no está vendiendo."; 
$l_tdr_newtdrcreated     = "¡Nueva ruta comercial creada!"; 
$l_tdr_tdrmodified       = "¡ruta comercial modificada!"; 
$l_tdr_doesntexist       = "¡La ruta comercial no existe!"; 
$l_tdr_notowntdr         = "¡No eres el propietario de esa ruta comercial!"; 
$l_tdr_tdrdeleted        = "La ruta comercial ha sido eliminada."; 
$l_tdr_globalset         = "Configuración global de las rutas comerciales"; 
$l_tdr_tdrsportsrc       = "Para rutas comerciales que tengan un puerto especial como origen, comercia"; 
$l_tdr_tdrescooped       = "Para las rutas comerciales via EspacioReal, ¿qué quieres hacer con la energía conseguida?"; 
$l_tdr_trade    	 = "Comerciar"; 
$l_tdr_keep    	 	 = "Almacenar"; 
$l_tdr_save    	 	 = "Guardar"; 
$l_tdr_globalsetsaved    = "Configuración global de las rutas comerciales guardada."; 
$l_tdr_engagenonexist    = "¡Has intentado usar una ruta comercial que no existe!"; 
$l_tdr_invalidspoint     = "¡El punto de origen no parece ser válido!"; 
$l_tdr_inittdr  	 = "¡No estás en el sector [tdr_source_id]! ¡Debes estar en el sector de origen antes de iniciar una ruta comercial!"; 
$l_tdr_invalidsrc        = "¡El planeta de origen no parece ser un planeta válido!"; 
$l_tdr_inittdrsector     = "¡No estás en el sector [tdr_source_sector_id]! ¡Debes estar en el sector de origen antes de iniciar una ruta comercial!"; 
$l_tdr_notyourplanet     = "¡No eres el propietario del planeta [tdr_source_name] en el sector [tdr_source_sector_id]!"; 
$l_tdr_invalidssector    = "¡El sector de origen no parece ser válido!"; 
$l_tdr_invaliddport      = "¡El puerto de destino no parece ser válido!"; 
$l_tdr_invaliddplanet    = "¡El planeta de destino no parece ser válido!"; 
$l_tdr_invaliddsector    = "¡El sector de destino no parece ser válido!"; 
$l_tdr_moreturnsneeded   = "Esta ruta comercial requiere [tdr_dist_triptime] turnos para ser completada. Solo te quedan [tdr_playerinfo_turns]."; 
$l_tdr_tdrhostdef        = "No puedes usar rutas comerciales entre sectores con defensas hostiles. Primero debes vencer las defensas."; 
$l_tdr_globalsetbuynothing= "¡Tu configuración global ha sido establecida para no comprar nada! ¡Solo gastarías turnos haciendo esta ruta!"; 
$l_tdr_nosrcporttrade    = "No está permitido el comercio con el puerto de origen."; 
$l_tdr_tradesrcportoutsider= "No está permitido el comercio en el punto de origen para los extranjeros."; 
$l_tdr_nodestporttrade   = "No está permitido el comercio desde el puerto de destino."; 
$l_tdr_tradedestportoutsider= "No está permitido el comercio en el puerto de destino para los extranjeros."; 
$l_tdr_tdrres  		 = "Resultados de la Ruta Comercial"; 
$l_tdr_bought  		 = "Comprado"; 
$l_tdr_nothingtotrade    = "Nada con que comerciar"; 
$l_tdr_sold   	  	 = "Vendido"; 
$l_tdr_ore    		 = "Minerales"; 
$l_tdr_portisfull        = "El puerto está lleno"; 
$l_tdr_goods    	 = "bienes"; 
$l_tdr_organics 	 = "orgánicos"; 
$l_tdr_energy   	 = "energía"; 
$l_tdr_portisempty       = "El puerto está vacío"; 
$l_tdr_loaded   	 = "Cargado"; 
$l_tdr_nothingtoload     = "Nada que cargar"; 
$l_tdr_scooped  	 = "Conseguido"; 
$l_tdr_dumped   	 = "Dejado"; 
$l_tdr_planetisovercrowded= "El planeta está superpoblado"; 
$l_tdr_nothingtodump     = "Nada que dejar"; 
$l_tdr_onlyonewaytdr     = "No se ha hecho nada. La ruta comercial era solo de una dirección."; 
$l_tdr_profit 		 = "Beneficio"; 
$l_tdr_cost   		 = "Coste"; 
$l_tdr_totalprofit       = "Beneficio Total"; 
$l_tdr_totalcost         = "Coste Total"; 
$l_tdr_credits  	 = "Créditos"; 
$l_tdr_turnsused         = "Turnos usados"; 
$l_tdr_turnsleft         = "Turnos restantes"; 
$l_tdr_notowner = "No eres el propietario de esta ruta comercial"; 

// IGB.php

$l_igb_credit_symbol = "C"; 
$l_igb_title    = "El Banco Intergaláctico"; 
$l_igb_humor    = "All your base are belong to us."; 
$l_igb_malfunction      = "Esta terminal de IGB funciona defectuosamente. El Banco Intergaláctico desea pedirle disculpas por cualquier inconveniente ocasionado."; 
$l_igb_quit     = "Salir"; 
$l_igb_login    = "Conectar"; 
$l_igb_welcometoigb     = "Bienvenido a esta Terminal del Banco Intergaláctico"; 
$l_igb_accountholder    = "Propietario de la Cuenta"; 
$l_igb_shipaccount      = "Cuenta de la Nave"; 
$l_igb_igbaccount       = "Cuenta de IGB"; 
$l_igb_operations       = "Operaciones"; 
$l_igb_withdraw = "Retirar"; 
$l_igb_deposit  = "Depositar"; 
$l_igb_transfer = "Transferir"; 
$l_igb_back     = "Volver"; 
$l_igb_logout   = "Desconectar"; 
$l_igb_withdrawfunds    = "Retirar Fondos"; 
$l_igb_fundsavailable   = "Fondos disponibles"; 
$l_igb_selwithdrawamount        = "Por favor, seleccione la cantidad a retirar"; 
$l_igb_depositfunds     = "Depositar Fondos"; 
$l_igb_seldepositamount = "Por favor, seleccione la cantidad a depositar"; 
$l_igb_transfertype     = "Tipo de Transferencia"; 
$l_igb_toanothership    = "A otra nave"; 
$l_igb_shiptransfer     = "Transferir entre Naves"; 
$l_igb_fromplanet       = "De un planeta a otro"; 
$l_igb_unnamed  = "Sin nombre"; 
$l_igb_in       = "en"; 
$l_igb_none     = "Ninguno"; 
$l_igb_destination      = "Destino"; 
$l_igb_planettransfer   = "Transferir entre Planetas"; 
$l_igb_sendyourself     = "¡No puede enviarse dinero a usted mismo!"; 
$l_igb_unknowntargetship        = "¡Nave de destino desconocida!"; 
$l_igb_min_turns        = "El jugador [igb_target_char_name] debe haber jugado al menos [igb_min_turns] turnos antes de recibir el dinero."; 
$l_igb_min_turns2       = "Usted debe haber jugado al menos [igb_min_turns] turnos antes de poder enviar dinero."; 
$l_igb_mustwait = "Usted ya ha realizado una transferencia a [igb_target_char_name] en los últimos [igb_trate] minutos. Debe esperar [igb_difftime] minutos antes de poder volver a transferir créditos a ese jugador."; 
$l_igb_maxtransfer      = "Máxima transferencia permitida"; 
$l_igb_unlimited        = "Ilimitada"; 
$l_igb_maxtransferpercent       = "La máxima transferencia permitida es un<br> ([igb_percent]% de los bienes netos)"; 
$l_igb_recipient        = "Receptor"; 
$l_igb_seltransferamount        = "Por favor, selecciona la cantidad a transferir"; 
$l_igb_transferrate     = "La tasa actual para las transferencias es un [igb_num_percent]% de la cantidad total. Será deducida automáticamente de la cantidad transferida."; 
$l_igb_errplanetsrcanddest      = "El mismo planeta no puede ser a la vez origen y destino."; 
$l_igb_errunknownplanet = "¡Error en la BD! ¡Planeta desconocido!"; 
$l_igb_errnotyourplanet = "Usted no puede transferir dinero desde/hacia un planeta del que sea propietario."; 
$l_igb_srcplanet        = "Orig -> Planeta"; 
$l_igb_destplanet       = "Dest -> Planeta"; 
$l_igb_transferrate2     = "La tasa actual para transferencias es un [igb_num_percent]% de la cantidad total. Será automáticamente deducida de la cantidad que usted transfiera."; 
$l_igb_errsendyourself  = "¡No puede enviarse dinero a usted mismo!"; 
$l_igb_min_turns3        = "El jugador [igb_target_char_name] debe haber jugado al menos [igb_min_turns] turnos antes de que pueda recibir el dinero."; 
$l_igb_min_turns4       = "Usted debe jugar al menos [igb_min_turns] turnos antes de poder enviar dinero."; 
$l_igb_mustwait2 = "Usted ya ha realizado una transferencia a [igb_target_char_name] en los últimos [igb_trate] minutos. Debe esperar [igb_difftime] minutos antes de que pueda volver a transferir créditos a ese jugador."; 
$l_igb_invalidtransferinput     = "Cantidad para transferir no válida."; 
$l_igb_nozeroamount     = "La cantidad a transferir no puede ser cero."; 
$l_igb_notenoughcredits = "Usted no tiene suficientes créditos para realizar esta operación."; 
$l_igb_amounttoogreat   = "La cantidad que ha introducido es mayor que la cantidad máxima permitida para transferencias."; 
$l_igb_transfersuccessful       = "Transferencia realizada con éxito"; 
$l_igb_creditsto        = "créditos han sido transferidos a"; 
$l_igb_transferamount   = "Transferir Cantidad"; 
$l_igb_transferfee      = "Cuota de la Transferencia"; 
$l_igb_amounttransferred        = "Cantidad Transferida"; 
$l_igb_notenoughcredits2        = "No hay suficientes créditos en el planeta de origen para completar la transacción."; 
$l_igb_to       = "hacia"; 
$l_igb_ctransferredfrom = "créditos han sido transferidos desde"; 
$l_igb_invaliddepositinput      = "Cantidad a depositar no válida."; 
$l_igb_nozeroamount2    = "La cantidad a depositar no puede ser cero."; 
$l_igb_operationsuccessful      = "Operación realizada con éxito"; 
$l_igb_creditstoyou     = "Créditos han sido transferidos a tu cuenta de IGB."; 
$l_igb_accounts = "Cuentas"; 
$l_igb_invalidwithdrawinput     = "Cantidad a retirar no válida."; 
$l_igb_nozeroamount3    = "La cantidad a retirar no puede ser cero."; 
$l_igb_creditstoyourship        = "Créditos han sido transferidos a la cuenta de tu nave."; 
$l_igb_igberrreport     = "Informe de Errores de IGB"; 
$l_igb_source   = "Origen"; 
$l_igb_loans = "Préstamos"; 
$l_igb_loanstatus = "Estado de los Préstamos"; 
$l_igb_currentloan = "Total del Préstamo Actual"; 
$l_igb_maxloanpercent = "Prestamo máximo permitido<br>([igb_percent]% de los bienes netos)"; 
$l_igb_loanamount = "Introduce la cantidad del préstamo"; 
$l_igb_borrow = "Solicitar"; 
$l_igb_loanrates     = "Todos los préstamos incurren en una única cuota del [factor]% del total del préstamo. Adicionalmente, usted será cargado un [interest]% en intereses cada turno que pase hasta que el préstamo sea devuelto."; 
$l_igb_invalidamount = "Ha introducido una cantidad no válida."; 
$l_igb_notwoloans = "No puede pedir un préstamo sin haber devuelto previamente el primero."; 
$l_igb_loantoobig = "No le está permitido solicitar un préstamo de tantos créditos."; 
$l_igb_takenaloan = "ha pedido un préstamo"; 
$l_igb_loancongrats = "¡Enhorabuena! ¡Usted ha solicitado un préstamo con el consorcio bancario más amigable!"; 
$l_igb_loantransferred = "Cantidad transferida a su cuenta de la nave"; 
$l_igb_loanfee = "Cuota única por el préstamo"; 
$l_igb_amountowned = "Cantidad total debida a IGB"; 
$l_igb_loanreminder = "Recordatorio amistoso: si usted no ha devuelto el préstamo en un total de [hours]h [mins]m, nos veremos forzados a invalidar la cuenta de su nave en los puertos especiales.<br><br>\"IGB, el proveedor de sus sueños\"";
$l_igb_loantimeleft = "Tiempo que le queda para realizar el pago"; 
$l_igb_loanlate = "¡El pago llega con retraso!"; 
$l_igb_repayamount = "Introduzca la cantidad a devolver"; 
$l_igb_repay = "Devolver"; 
$l_igb_notrepay = "No tiene préstamos que devolver"; 
$l_igb_notenoughrepay = "No tiene suficientes créditos en la cuenta de su nave para realizar esta operación."; 
$l_igb_payloan = "Pago del Préstamo"; 
$l_igb_loanthanks = "Su pago ha sido recibido. Gracias por hacer negocios con IGB."; 
$l_igb_credsconsol = "Orig -> Créditos Totales a consolidar"; 
$l_igb_transferrate3     = "La tasa actual para consolidar es de un [igb_num_percent]% de la cantidad total. Será automaticamente deducida de la cantidad consolidada. La transferencia costará un turno por cada uno de los [nbplanets] planetas afectados."; 
$l_igb_currentpl = "Créditos en el planeta"; 
$l_igb_consolrates = "Usted puede especificar un margen de crédito. Los planetas con menos créditos que el Mínimo y con más créditos que el Máximo no se verán afectados. Establezca a 0 para que no existan límites"; 
$l_igb_minimum = "Mínimo"; 
$l_igb_maximum = "Máximo"; 
$l_igb_planetconsolidate = "Consolidar Planeta"; 
$l_igb_compute = "Computar"; 
$l_igb_plaffected = "Total de planetas afectados"; 
$l_igb_turncost = "Coste total de turnos"; 
$l_igb_consolidate = "Consolidar"; 
$l_igb_conspl = "Consolidar los Créditos a un solo planeta"; 
$l_igb_notenturns = "No tiene suficientes turnos para realizar esta operación"; 

// combat.php
$l_cmb_atleastoneturn   = "Necesitas al menos un turno para atacar un planeta."; 
$l_cmb_shipenergybb     = "Energía de la nave antes de los disparos"; 
$l_cmb_shipenergyab     = "Energía de la nave tras los disparos"; 
$l_cmb_shipenergyas     = "Energía de la nave tras los escudos"; 
$l_cmb_shiptorpsbtl     = "Torpedos a bordo antes del lanzamiento de torpedos"; 
$l_cmb_shiptorpsatl     = "Torpedos a bordo tras el lanzamiento de torpedos"; 
$l_cmb_planettorpdamage = "Daño de los torpedos del planeta"; 
$l_cmb_attackertorpdamage       = "Daños de los torpedos del atacante"; 
$l_cmb_beams    = "Disparos"; 
$l_cmb_fighters = "Cazas"; 
$l_cmb_shields  = "Escudos"; 
$l_cmb_torps    = "Torpedos"; 
$l_cmb_torpdamage       = "Daño de los torpedos"; 
$l_cmb_armor    = "Armadura"; 
$l_cmb_you      = "Tú"; 
$l_cmb_planet   = "Planeta"; 
$l_cmb_combatflow       = "Seguimiento del combate"; 
$l_cmb_defender = "Defensor"; 
$l_cmb_attackingplanet  = "Atacando al planeta en el sector"; 
$l_cmb_youfireyourbeams = "Disparas tus lásers"; 
$l_cmb_defenselost      = "La defensa planetaria ha perdido [cmb_planetfighters] cazas con tus disparos"; 
$l_cmb_defenselost2     = "La defensa planetaria ha perdido [cmb_attackerbeams] cazas, ¡pero hay más viniendo"; 
$l_cmb_planetarybeams   = "Los disparos planetarios han destruido [cmb_temp] de tus cazas"; 
$l_cmb_planetarybeams2   = "Los disparos planetarios han destruido [cmb_planetbeams] de tus cazas"; 
$l_cmb_youdestroyedplanetshields        = "Tus disparos han destruido los escudos del planeta"; 
$l_cmb_beamsexhausted   = "Has destruido [cmb_attackerbeams] escudos planetarios antes de que tus disparos se agotasen"; 
$l_cmb_breachedyourshields      = "Los disparos planetarios han abierto brecha en tus escudos"; 
$l_cmb_destroyedyourshields     = "Los disparos planetarios han destruido [cmb_planetbeams] de tus escudos"; 
$l_cmb_breachedyourarmor        = "Los disparos planetarios han abierto brecha en tu armadura"; 
$l_cmb_destroyedyourarmor       = "Los disparos planetarios han destruido [cmb_planetbeams] puntos de armadura"; 
$l_cmb_torpedoexchangephase     = "Fase de Intercambio de Torpedos"; 
$l_cmb_nofightersleft   = "Tus torpedos han destruido [cmb_planetfighters] cazas planetarios. Ya no quedan cazas"; 
$l_cmb_youdestroyfighters       = "Tus torpedos han destruido [cmb_attackertorpdamage] cazas planetarios"; 
$l_cmb_planettorpsdestroy       = "Los torpedos planetarios han destruido [cmb_temp] de tus cazas"; 
$l_cmb_planettorpsdestroy2      = "Los torpedos planetarios han destruido [cmb_planettorpdamage] de tus cazas"; 
$l_cmb_torpsbreachedyourarmor   = "Los torpedos planetarios han abierto brecha en tu armadura"; 
$l_cmb_planettorpsdestroy3      = "Los torpedos planetarios han destruido [cmb_planettorpdamage] puntos de armadura"; 
$l_cmb_youdestroyedallfighters  = "Tus torpedos han destruido todos los cazas planetarios"; 
$l_cmb_youdestroyplanetfighters = "Tus torpedos han destruido [cmb_attackertorpdamage] cazas planetarios"; 
$l_cmb_fightercombatphase       = "Fase de Combate de Cazas"; 
$l_cmb_youdestroyedallfighters2  = "Tus cazas han destruido todos los cazas planetarios."; 
$l_cmb_youdestroyplanetfighters2        = "Tus cazas han destruido [cmb_attackerfighters] cazas planetarios"; 
$l_cmb_allyourfightersdestroyed = "Todos tus cazas han sido destruidos"; 
$l_cmb_fightertofighterlost     = "Has perdido [cmb_planetfighters] cazas en combate caza contra caza"; 
$l_cmb_youbreachedplanetshields = "Tus cazas han abierto brecha en los escudos planetarios"; 
$l_cmb_shieldsremainup  = "Tus cazas han destruido [cmb_attackerfighters] escudos planetarios, pero todavía están activos"; 
$l_cmb_fighterswarm     = "Los cazas planetarios rodean tu nave, hay una brecha en tu armadura"; 
$l_cmb_swarmandrepel    = "Los cazas planetarios rodean tu nave, pero la armadura los repele"; 
$l_cmb_engshiptoshipcombat      = "Entrando en combate nave contra nave."; 
$l_cmb_shipdock = "¡Hay [cmb_shipsonplanet] naves atracadas en el Espaciopuerto!"; 
$l_cmb_approachattackvector     = "está acercándose en un vector de ataque"; 
$l_cmb_noshipsdocked    = "¡NO hay naves atracadas en el Espaciopuerto!"; 
$l_cmb_yourshipdestroyed        = "¡Tu nave ha sido destruida!"; 
$l_cmb_escapepod        = "¡Afortunadamente tenías una cápsula de salvamento!"; 
$l_cmb_finalcombatstats = "Estadísticas Finales del Combate"; 
$l_cmb_youlostfighters  = "Has perdido [cmb_fighters_lost] de un total de [cmb_playerinfo_ship_fighters] cazas."; 
$l_cmb_youlostarmorpoints       = "has perdido [cmb_armor_lost] de un total de [cmb_playerinfo_armour_pts] puntos de armadura. Te quedan [cmb_attackerarmor] puntos."; 
$l_cmb_energyused       = "Has usado [cmb_energy_lost] energía, de un total de [cmb_playerinfo_ship_energy] energía."; 
$l_cmb_planetdefeated   = "Planeta vencido"; 
$l_cmb_citizenswanttodie        = "Los ciudadanos de este planeta han decidido que prefieren morir antes que servir a un gobernante tan patético como tú. Han usado un taladro laser para hacer un gran agujero hacia el corazón del planeta. Apenas has tenido tiempo de escapar a una órbita segura antes de que todo el planeta haya sido reducido a una bola de lava fundida."; 
$l_cmb_youmaycapture    = "Puedes <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>capturar</a> el planeta o dejarlo indefenso."; 
$l_cmb_youmaycapture2   = "Puedes <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>capturar</a> el planeta o dejarlo indefenso."; 
$l_cmb_planetnotdefeated        = "Planeta no vencido"; 
$l_cmb_planetstatistics = "Estadísticas del planeta"; 
$l_cmb_fighterloststat  = "Cazas perdidos: [cmb_fighters_lost] de un total de [cmb_planetinfo_fighters] ([cmb_planetfighters] vivos)"; 
$l_cmb_energyleft       = "Energía restante"; 
$l_cmb_startingstats    = "Estadísticas iniciales"; 
$l_cmb_statattackerbeams        = "Disparos atacante"; 
$l_cmb_statattackerfighters     = "Cazas atacante"; 
$l_cmb_statattackershields      = "Escudos atacante"; 
$l_cmb_statattackertorps        = "Torpedos atacante"; 
$l_cmb_statattackerarmor        = "Armadura atacante"; 
$l_cmb_statattackertorpdamage   = "Daño torpedos atacante"; 
$l_cmb_isattackingyou   = "te está atacando"; 
$l_cmb_beamexchange     = "Intercambio de disparos"; 
$l_cmb_beamsdestroy     = "Tus disparos destruyen [cmb_lost] cazas"; 
$l_cmb_beamsdestroy2    = "Tus disparos destruyen [cmb_attackerbeams] cazas, pero hay más viniendo"; 
$l_cmb_nobeamsareleft   = "¡No te quedan disparos para destruir los cazas que se acercan!"; 
$l_cmb_beamshavenotarget        = "Tus disparos no tienen cazas marcados como objetivo para destruir"; 
$l_cmb_fighterdestroyedbybeams  = "[cmb_targetinfo_ship_name] destruyó [cmb_lost] de tus cazas con disparos<BR>"; 
$l_cmb_beamsdestroystillhave    = "[cmb_targetinfo_ship_name] ha destruido [cmb_targetbeams] de tus cazas con disparos, pero aún te quedan [cmb_attackerfighters]"; 
$l_cmb_fighterunhindered        = "Tus cazas atacaron sin problemas, al enemigo ya no le quedaban disparos."; 
$l_cmb_youhavenofightersleft    = "No te quedan cazas con los que atacar"; 
$l_cmb_breachedsomeshields      = "Has abierto brecha en los escudos de [cmb_targetinfo_ship_name] con tus disparos"; 
$l_cmb_shieldsarehitbybeams     = "Los escudos de [cmb_targetinfo_ship_name] han sido atacos por [cmb_attackerbeams] de daño por tus disparos"; 
$l_cmb_nobeamslefttoattack      = "No te quedan disparos para atacar los escudos de [cmb_targetinfo_ship_name]"; 
$l_cmb_yourshieldsbreachedby    = "Los disparos de [cmb_targetinfo_ship_name] han abierto brecha en tus escudos"; 
$l_cmb_yourshieldsarehit        = "Los disparos de [cmb_targetinfo_ship_name] han alcanzado a tus escudos por [cmb_targetbeams] de daño."; 
$l_cmb_hehasnobeamslefttoattack = "A [cmb_targetinfo_ship_name] no le quedan disparos para atacar tus escudos"; 
$l_cmb_yourbeamsbreachedhim     = "Tus disparos han abierto brecha en la armadura de [cmb_targetinfo_ship_name]"; 
$l_cmb_yourbeamshavedonedamage  = "Tus disparos han hecho [cmb_attackerbeams] de daño a la armadura de [cmb_targetinfo_ship_name]"; 
$l_cmb_nobeamstoattackarmor     = "No te quedan disparos para atacar la armadura de [cmb_targetinfo_ship_name]"; 
$l_cmb_yourarmorbreachedbybeams = "Hay una brecha en tu armadura debida a los disparos de [cmb_targetinfo_ship_name]"; 
$l_cmb_yourarmorhitdamaged      = "Tu armadura ha sido alcanzada por [cmb_targetbeams] de daño por los disparos de [cmb_targetinfo_ship_name]"; 
$l_cmb_torpedoexchange  = "Intercambio de torpedos"; 
$l_cmb_hehasnobeamslefttoattackyou      = "A [cmb_targetinfo_ship_name] no le quedan disparos para atacar tu armadura"; 
$l_cmb_yourtorpsdestroy = "Tus torpedos han destruido [cmb_lost] de los cazas de [cmb_targetinfo_ship_name]"; 
$l_cmb_yourtorpsdestroy2        = "Tus torpedos han destruido [cmb_attackertorpdamage] de los cazas de [cmb_targetinfo_ship_name]"; 
$l_cmb_youhavenotorpsleft       = "No te quedan torpedos para atacar los cazas de [cmb_targetinfo_ship_name]"; 
$l_cmb_hehasnofighterleft       = "A [cmb_targetinfo_ship_name] no le quedan cazas para destruir tus torpedos"; 
$l_cmb_torpsdestroyyou  = "Los torpedos de [cmb_targetinfo_ship_name] destruyen [cmb_lost] de tus cazas"; 
$l_cmb_someonedestroyedfighters = "[cmb_targetinfo_ship_name] ha destruido [cmb_targettorpdmg] de tus cazas con torpedos"; 
$l_cmb_hehasnotorpsleftforyou   = "A [cmb_targetinfo_ship_name] no le quedan torpedos para atacar a tus cazas"; 
$l_cmb_youhavenofightersanymore = "No te quedan cazas para destruir los torpedos de [cmb_targetinfo_ship_name]"; 
$l_cmb_youbreachedwithtorps     = "Has abierto brecha en la armadura de [cmb_targetinfo_ship_name] con tus torpedos"; 
$l_cmb_hisarmorishitbytorps     = "La armadura de [cmb_targetinfo_ship_name] ha sido alcanzada por [cmb_attackertorpdamage] de daño por tus torpedos"; 
$l_cmb_notorpslefttoattackarmor = "No te quedan torpedos para atacar la armadura de [cmb_targetinfo_ship_name]"; 
$l_cmb_yourarmorbreachedbytorps = "Los torpedos de [cmb_targetinfo_ship_name] han abierto una brecha en tu armadura"; 
$l_cmb_yourarmorhitdmgtorps     = "Tu armadura es alcanzada por [cmb_targettorpdmg] de daño por los torpedos de [cmb_targettorpdmg]"; 
$l_cmb_hehasnotorpsforyourarmor = "A [cmb_targetinfo_ship_name] no le quedan torpedos para atacar tu armadura"; 
$l_cmb_fightersattackexchange   = "Intercambio de Ataques de Cazas"; 
$l_cmb_enemylostallfighters     = "[cmb_targetinfo_ship_name] ha perdido todos sus cazas"; 
$l_cmb_helostsomefighters       = "[cmb_targetinfo_ship_name] ha perdido [cmb_attackerfighters] cazas."; 
$l_cmb_youlostallfighters       = "Has perdido todos tus cazas"; 
$l_cmb_youalsolostsomefighters  = "Has perdido [cmb_targetfighters] cazas."; 
$l_cmb_hehasnofightersleftattack        = "A [cmb_targetinfo_ship_name] no le quedan cazas para atacar a tus cazas"; 
$l_cmb_younofightersattackleft  = "No te quedan cazas para atacar a los cazas de [cmb_targetinfo_ship_name]"; 
$l_cmb_youbreachedarmorwithfighters     = "Has abierto brecha en la armadura de [cmb_targetinfo_ship_name] con tus cazas"; 
$l_cmb_youhitarmordmgfighters   = "Has alcanzado la armadura de [cmb_targetinfo_ship_name] por [cmb_attackerfighters] de daño con tus cazas"; 
$l_cmb_youhavenofighterstoarmor = "No te quedan cazas para atacar la armadura de [cmb_targetinfo_ship_name]"; 
$l_cmb_hasbreachedarmorfighters = "[cmb_targetinfo_ship_name] ha abierto brecha en tu armadura con sus cazas"; 
$l_cmb_yourarmorishitfordmgby   = "Tu armadura ha sido alcanzada por [cmb_targetfighters] de daño por los cazas de [cmb_targetinfo_ship_name]"; 
$l_cmb_nofightersleftheforyourarmor     = "A [cmb_targetinfo_ship_name] no le quedan cazas para atacar tu armadura"; 
$l_cmb_hehasbeendestroyed       = "[cmb_targetinfo_ship_name] ha sido destruido"; 
$l_cmb_escapepodlaunched        = "¡Ha sido lanzada una cápsula de salvamento!"; 
$l_cmb_yousalvaged      = "Has capturado [cmb_salv_ore] unidades de minerales, [cmb_salv_organics] unidades de orgánicos, [cmb_salv_goods] unidades de bienes, y has capturado un [cmb_salvage_rate]% de la nave por un valor de [cmb_salvage] créditos.<BR>Tu puntuación ha cambiado en [cmb_number_rating_change] puntos."; 
$l_cmb_youdidntdestroyhim       = "No has destruido [cmb_targetinfo_ship_name]"; 
$l_cmb_shiptoshipcombatstats    = "Estadísticas de combate Nave contra Nave"; 

// check_mines.php

$l_chm_youhitsomemines  = "¡Has golpeado [chm_roll] minas!"; 
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] ha golpeado [chm_roll] minas en el sector [chm_sector]."; 
$l_chm_youlostminedeflectors    = "Has perdido [chm_roll] deflectores de minas."; 
$l_chm_youlostallminedeflectors = "Has perdido todos tus deflectores de minas."; 
$l_chm_youhadnominedeflectors  = "No tienes deflectores de minas."; 
$l_chm_yourshieldshitforminesdmg        = "Tus escudos han sido alcanzados por [chm_mines_left] de daño."; 
$l_chm_yourshieldsaredown       = "¡Tus escudos están desactivados!"; 
$l_chm_youlostallyourshields    = "¡Has perdido todos tus escudos!"; 
$l_chm_yourarmorhitforminesdmg  = "Tu armadura ha sido alcanzada por [chm_mines_left] de daño."; 
$l_chm_yourhullisbreached       = "¡Hay una brecha en tu casco!"; 
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] fue destruido por minas en el sector [chm_sector]"; 
$l_chm_yourshiphasbeendestroyed = "¡Tu nave ha sido destruida!"; 
$l_chm_luckescapepod    = "¡Afortunadamente tienes una cápsula de salvamento!"; 

// check_fighters.php

$l_chf_youretreatback   = "Regresas a tu localización anterior"; 
$l_chf_notenoughcreditstoll     = "No tienes suficientes créditos para pagar el peaje."; 
$l_chf_movefailed       = "Movimiento fallido."; 
$l_chf_youpaidsometoll  = "Has pagado [chf_tollstring] créditos por el peaje."; 
$l_chf_thefightersdetectyou     = "¡Los cazas te han detectado!"; 
$l_chf_therearetotalfightersindest      = "Hay un total de [chf_total_sector_fighters] cazas en tu sector de destino."; 
$l_chf_creditsdemanded  = "Piden [chf_number_fighterstoll] créditos para entrar en este sector."; 
$l_chf_youcanretreat    = "Puedes <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Retroceder</B> - Te costará un turno extra.<BR></INPUT>"; 
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Pagar</B> el peaje y entrar sin correr riesgo por los cazas.<BR></INPUT>"; 
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Luchar</B> - debes derrotar a todos los cazas para entrar en el sector.<BR></INPUT>"; 
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Ocultar</B> - Usar tu dispositivo de ocultación e intentar evitar a los cazas.<BR></INPUT>"; 
$l_chf_go       = "Adelante"; 

// mines.php

$l_mines_title			= "Instalar Minas de sector y Cazas"; 
$l_mines_noturn		 	= "Necesitas al menos un turno para instalar defensas de sector."; 
$l_mines_nopermit		= "No está permitido instalar Minas y Cazas en este sector."; 
$l_mines_nodeploy		= "No puedes instalarlo aquí. Otra nave o Alianza tiene minas o cazas en este sector."; 
$l_mines_info1			= "Actualmente estás en el sector [sector]. Hay [mines] minas y [fighters] cazas aquí."; 
$l_mines_info2			= "Tienes [mines] minas y [fighters] cazas disponibles para instalar"; 
$l_mines_deploy			= "Instalar"; 
$l_mines_deployed		= "Instalado"; 
$l_mines_att			= "Atacar"; 
$l_mines_toll			= "Peaje"; 
$l_mines_notorps		= "No tienes suficientes torpedos."; 
$l_mines_nofighters		= "No tienes suficientes cazas"; 
$l_mines_dmines			= "Instaladas [mines] minas."; 
$l_mines_dfighter		= "Instalados [fighters] cazas en modo [mode]."; 
$l_mines_fmode			= "Modo de los cazas"; 

//alliance-planets.php

$l_teamplanet_title		= "Informe de Alianza Planetaria"; 
$l_teamplanet_notally		= "No estás en una alianza"; 
$l_teamplanet_personal		= "Mostrar planetas personales"; 
$l_teamplanet_noplanet		= "Tu alianza no tiene planetas"; 

$l_feedback_title		= "Enviar comentarios"; 
$l_feedback_to			= "PARA:"; 
$l_feedback_from		= "DE:"; 
$l_feedback_topi		= "ASUNTO:"; 
$l_feedback_feedback		= "Comentarios"; 
$l_feedback_message		= "MENSAJE:"; 
$l_feedback_messent		= "Mensaje Enviado"; 
$l_feedback_subj		= "Comentarios WTW"; 
$l_feedback_info		= "Por favor, envía comentarios solo en inglés. Gracias.";  // gameadmins put all your languages here

// corp.php
$l_corpm_title			= "Menú de la Corporación"; 
$l_corpm_tocorp			= "¡El planeta es ahora un Planeta de la Corporación!"; 
$l_corpm_topersonal		= "¡El planeta es ahora un Planeta Personal!"; 
$l_corpm_exploit		= "Has interceptado un mensaje borg cortado en tu escaner... deberías empezar a preocuparte..."; 


// login.php login2.php
$l_login_title			= "Conectar";  
$l_login_email			= "Dirección de email:"; 
$l_login_pw			= "Contraseña:"; 
$l_login_chooseres		= "Imposible determinar tu resolución de pantalla. Por favor, escoge la que mejor se ajuste:"; 
$l_login_newp			= "Si eres un jugador nuevo, pulsa <A HREF=\"new.php\">aquí</A>."; 
$l_login_prbs			= "¿Problemas?"; 
$l_login_emailus		= "Mándanos un email"; 
$l_login_sclosed		= "Servidor Cerrado"; 
$l_login_closed_message		= "Servidor cerrado hasta futuras notificaciones."; 
$l_login_title2			= "Fase Dos de la Conexión";  
$l_login_banned			= "<b>Has sido vetado de este juego por el administrador. Ya no eres bienvenido a jugar en este servidor. La próxima vez, compórtate.</b>"; 
$l_login_died			= "Tu nave ha sido destruida, pero tú y tu tripulación os habéis salvado gracias a una cápsula de salvamento. Pulsa <A HREF=main.php>aquí</A> para continuar con una nueva nave."; 
$l_login_newbie			= "Debido a la seriedad de este crimen y el terrible ataque contra ti, la Federación ha decidido proveerte sin cargo alguno de una clonación de tus restos. Lamentablemente, incluso a estas alturas los nuevos clones no pueden poseer propiedades, aparte de las fundamentales para poder vivir. Te será otorgado una nave básica y unos cuantos créditos para que comiences. Esperamos que te vaya mejor en tu nueva vida."; 

$l_login_newlife		= "Pulsa <A HREF=main.php>aquí</A> para continuar una nueva vida."; 
$l_login_looser			= "No tenías cápsula de salvamento, y debido a tu modesto éxite en esta vida, la Federación no accede a clonarte. Tus restos caerán probablemente en un campo gravitatorio, con la esperanza de ser usados para crear vida en cualquier lugar... dentro de un billón de años.<br><br>Mejor suerte en tu siguiente partida..."; 
$l_login_4gotpw1		= "La contraseña que has introducido es incorrecta<br><br>Si has olvidado tu contraseña,"; 
$l_login_4gotpw2		= "para que te sea enviada por email.<br><br>De otro modo,"; 
$l_login_4gotpw3		= "inténtalo de nuevo. Intento de conexión con la dirección IP de"; 
$l_login_noone			= "¡No existe ese jugador! - Crea un nuevo jugador <A HREF=new.php>aquí</A>."; 
$l_login_lang = "Idioma"; 
$l_login_settings = "Configuración del Juego"; 
$l_login_change = "Cambiar"; 

// new.php new2.php
$l_new_title			= "Crear Nuevo Jugador";  
$l_new_title2			= "Fase Dos de la Creación de un Nuevo Jugador";  
$l_new_shipname			= "Nombre de la Nave"; 
$l_new_pname			= "Nombre del Personaje del Jugador"; 
$l_new_info			= "Prometemos no dar (o vender) tu dirección de email a nadie. Se requiere para enviarte la contraseña generada por el servidor."; 
$l_new_closed_message		= "Juego cerrado por Partida de Torneo"; 
$l_new_blank			= "El email, nombre de la nave, y nombre del personaje no pueden estar en blanco."; 
$l_new_inuse			= "La dirección de email ya está en uso."; 
$l_new_4gotpw1			= "Si has olvidado tu contraseña,"; 
$l_new_4gotpw2			= "para que te sea enviada por email."; 
$l_new_inusechar		= "El nombre de personaje $character ya está en uso."; 
$l_new_inuseship		= "El nombre de la nave $shipname ya está en uso."; 
$l_new_pwsent			= "La contraseña ha sido enviada a ${HTTP_POST_VARS['username']}"; 
$l_new_login			= "para ir a la pantalla de conexión"; 
$l_new_err			= "Por favor, ve atrás o <a href=new.php>pulsa aquí</a> e inténtalo de nuevo."; 
$l_new_topic			= "Contraseña de Traders"; 
$l_new_message			= "Saludos,\r\n\r\nAlguien desde la dirección IP $ip ha solicitado tu contraseña para Traders te sea enviada.\r\n\r\nTu contraseña es: [pass]\r\n\r\nGracias\r\n\r\nEl equipo web de Traders."; 

// logout.php

$l_logout_score			= "Tu puntuación actual es"; 
$l_logout_text			= "[name] está ahora desconectado. Pulsa <A HREF=index.php>aquí</A> para volver al juego."; 


// mail.php
$l_mail_title			= "Enviar Contraseña";  
$l_mail_noplayer		= "¡No existe ese jugador! - Crea un nuevo jugador desde <a href=new.php>aquí</a>."; 
$l_mail_sent			= "La contraseña ha sido enviada a"; 
$l_mail_topic			= "Contraseña de $game_name"; 
$l_mail_message			= "Saludos,\r\n\r\nAlguien desde la dirección IP $ip ha solicitado que tu contraseña para $game_name te sea enviada.\r\n\r\nTu contraseña es: [pass]\r\n\r\nGracias\r\n\r\nEl equipo web de $game_name."; 



// global_funcs.php
$l_global_mmenu			= "Pulsa <A HREF=main.php>aquí</A> para volver al menú principal."; 
$l_global_mlogin		= "Pulsa <A HREF=login.php>aquí</A> para volver a la pantalla de conexión."; 
$l_global_needlogin		= "Necesitas estar conectado, pulsa <A HREF=login.php>aquí</A>."; 
$l_global_died			= "¡El jugador está MUERTO! <a href=log.php>Aquí</a> está lo que ha ocurido<br><br>¡Mejor suerte la próxima vez!"; 
$l_global_warzone		= "¡La zona es una zona de guerra!"; 
$l_global_nzone			= "La zona es una zona neutral."; 
$l_global_team			= "La zona pertenece ahora a la alianza"; 
$l_global_player		= "La zona pertenece ahora al jugador"; 

// texts for the news flashes

$l_news_planets		  = " planetas"; 
$l_news_cols		      = "Millones de colonos"; 
$l_news_p_headline = "El Imperio de [player] tiene ahora "; 

$l_killheadline = " ha muerto en un accidente"; 
$l_news_killed = "[name] ha muerto en un trágico accidente hoy. Qué heroico - el capitán [name] era el último miembro a bordo de su nave, cuando notó que ya no quedaban cápsulas de salvamento para él. ¡Descanse en paz!"; 
$l_news_p_text5		= "El emergente imperio de [name] tiene ahora cinco planetas, ¡la BNN estará al tanto de las acciones de [name] en el futuro!"; 
$l_news_p_text10		= "El emergente imperio de [name] tiene ahora el control de diez planetas, ¡Informes de la BNN dicen que la progresiva expansión de [name] puede llevar a la guerra!"; 
$l_news_p_text25		= "El gran imperio de [name] ha colonizado ya 25 planetas, ¡en una entrevista, [name] anunció que considera ralentizar sus expansiones en el futuro!"; 
$l_news_p_text50		= "El enorme y vasto imperio de [name], representado por 50 planetas en toda la galaxia está consiguiendo una fuerza amenazadora. Uno de los reporteros de BNN descubrió que [name] está actualizando su nave, planeando una guerra masiva. ¡En una entrevista [name] anunció que esto se debe a motivos puramente devensivos!"; 
$l_news_c_text25		= "El creciente imperio de [name] tiene ahora 25 millones de colonos, la BNN prestará más atención a las acciones de [name] en el futuro, ¡pero es realmente obvio que los índices de natalidad van a explotar!"; 
$l_news_c_text100		= "El aspirante imperio de [name] tiene ahora 100 millones de colonos, ¡después de una explosión demográfica, las colonias de [name] parecen un buen lugar para que las familias se establezcan!"; 
$l_news_c_text500		= "El gran imperio de [name] tiene ahora 500 millones de colonos, [name] dijo en una entrevista que la colonización de la galaxia tan solo acaba de empezar"; 
$l_news_c_text1000		= "El inmenso imperio de [name] tiene ahora un billón de colonos, los reporteros de la BNN han descubierto que [name] está en posesión de algún tipo de extraño mecanismo de clonación que le permite crear nuevos colonos en cantidades industriales. Con esta cantidad de colonos, la fuerza económica de este imperio es enorme, la BNN espera que [name] no gaste su dinero en asuntos bélicos"; 


// Options.php



$l_opt_title = "Opciones"; 
$l_opt_chpass = "Cambiar cntraseña:"; 
$l_opt_curpass = "Contraseña actual:"; 
$l_opt_newpass = "Nueva contraseña:"; 
$l_opt_newpagain = "Nueva contraseña (de nuevo):"; 
$l_opt_userint = "Interfaz del usuario"; 
$l_opt_usenew = "¿Usar nuevo diseño?"; 
$l_opt_lang = "Idioma"; 
$l_opt_select = "Elije uno:"; 
$l_opt_enabled = "Activado"; 
$l_opt_save = "Guardar"; 



// Option2.php



$l_opt2_title = "Guardar Opciones"; 
$l_opt2_passunchanged = "La contraseña no ha sido modificada.<BR><BR>"; 
$l_opt2_srcpassfalse = "La contraseña original es incorrecta. La contraseña no ha sido modificada.<BR><BR>"; 
$l_opt2_newpassnomatch = "Los campos de la nueva contraseña no coinciden. La contraseña no ha sido modificada.<BR><BR>"; 
$l_opt2_passchanged = "Contraseña cambiada.<BR><BR>"; 
$l_opt2_passchangeerr = "Error al cambiar la contraseña<BR><BR>"; 
$l_opt2_userintup = "Interfaz del usuario actualizada.<BR><BR>"; 
$l_opt2_userintfail = "Error al actualizar la interfaz del usuario.<BR><BR>"; 
$l_opt2_chlang = "El idioma ha sido cambiado a [lang].<p>"; 
$l_opt2_dhtmlup = "Html Dinámico actualizado.<BR><BR>"; 
$l_opt2_dhtmlfail = "Error al actualizar html dinámico.<BR><BR>"; 

// Presets.php
$l_pre_title = "Cambiar Presets de EspacioReal"; 
$l_pre_exceed = "El preset [preset] excede el máximo de [sector_max]. No se ha guardado ningún preset.<BR><BR>";  
$l_pre_set = "Preset 1 fijado en [preset1], preset 2 fijado en [preset2] y preset 3 fijado en [preset3].<BR><BR>"; 
$l_pre_save = "Guardar"; 

// Mailto.php

$l_mt_title = "Enviar Mensaje"; 
$l_mt_from = "De:"; 
$l_mt_subject = "Asunto:"; 
$l_mt_message = "Mensaje:"; 
$l_mt_sent = "Mensaje envidao"; 
$l_mt_send = "Enviar"; 

// sector_fighters.php
$l_sf_attacking = "¡Los cazas de la defensa de sector te estan atacando!<br>"; 
$l_sf_destfight = "Tus disparos han destruido [lost] cazas<br>"; 
$l_sf_destfightb = "Tus disparos han destruido [lost] cazas<br>"; 
$l_sf_torphit = "Ataque de torpedos:"; 
$l_sf_destfightt = "Tus torpedos han destruido [lost] cazas<br>"; 
$l_sf_fighthit = "Ataque de Cazas:"; 
$l_sf_destfightall = "Has destruido todos los cazas.<br>"; 
$l_sf_destfightt2 = "Has destruido [lost] cazas.<br>"; 
$l_sf_lostfight = "Has perdido todos tus cazas.<br>"; 
$l_sf_lostfight2 = "Has perdido [lost] cazas.<br>"; 
$l_sf_armorbreach = "¡Han abierto brecha en tu armadura!<br>"; 
$l_sf_armorbreach2 = "Tu armadura ha sido alcanzada por [lost] de daño.<br>"; 
$l_sf_sendlog = "[player] ha destruido [lost] cazas de la defensa de sector [sector]"; 
$l_sf_lreport = "Has perdido [armor] puntos de armadura, [fighters] cazas, y has usado [torps] torpedos.<BR><BR>"; 
$l_sf_shipdestroyed = "¡Tu nave ha sido destruida!<BR><BR>"; 
$l_sf_sendlog2 = "Los cazas de la defensa de sector han destruido a [player] en el sector [sector]."; 
$l_sf_escape = "¡Afortunadamente tienes una cápsula de salvamento!<BR><BR>"; 

// Zone names

$l_zname[1] = "Espacio no cartografiado"; 
$l_zname[2] = "Espacio de la Federación"; 
$l_zname[3] = "Espacio de Libre Comercio"; 
$l_zname[4] = "Zona de Guerra"; 

// ADDITION TO warpedit2.php

$l_warp_cantsame = "No puedes crear un enlace cuando el origen es el mismo que el destino."; 

// Bounty
$l_by_title = "Recompensas"; 
$l_by_noturn = "Necesitas al menos un turno para ofrecer o modificar una recompensa."; 
$l_by_amount = "Cantidad de la Recompensa"; 
$l_by_place = "Ofrecer Recompensa"; 
$l_by_nobounties = "Actualmente no hay recompensas."; 
$l_by_bountyon = "Recompensa sobre"; 
$l_by_placedby = "Ofrecida por"; 
$l_by_thefeds  = "La Federación"; 
$l_by_cancel   = "Cancelar"; 
$l_by_yourself = "No puedes ofrecer una recompensa sobre ti mismo."; 
$l_by_notenough = "No tienes suficientes créditos para ofrecer una recompensa por esa cantidad."; 
$l_by_toomuch   = "No puedes ofrecer esa recompensa. La máxima recompensa permitida sobre otro jugador es $percent por ciento de tus bienes netos"; 
$l_by_zeroamount = "Las recompensas deben ser mayores que 0 créditos."; 
$l_by_placed     = "La recompensa ha sido establecida."; 
$l_by_nobounty = "Ya no existe esa recompensa."; 
$l_by_notyours = "Esa recompensa no ha sido establecida por ti."; 
$l_by_canceled = "La recompensa ha sido cancelada."; 
$l_by_action   = "Acción"; 
$l_by_placebounty = "Establecer o ver recompensas."; 
$l_by_moredetails = "Pulsa en el nombre para más detalles."; 
$l_by_fedbounty = "Al atacar a este jugador la Federación ofrecerá una recompensa por tu cabeza."; 
$l_by_fedbounty2 = "La Federación no aprueba el ataque a naves más pequeñas. Se ha ofrecido una recompensa por tu cabeza."; 
$l_by_notexists = "El jugador por el que ofreces una recompensa no existe."; 
$l_by_destroyed = "No puedes ofrecer una recompensa por un jugador con una nave destruida."; 
$l_log_text[LOG_BOUNTY_CLAIMED] = "Reclamas una recompensa de [amount] créditos por la destrucción de la nave perteneciente a [bounty_on]. La recompensa fue ofrecida por [placed_by]."; 
$l_log_title[LOG_BOUNTY_CLAIMED] = "Recompensa Reclamada."; 
$l_log_text[LOG_BOUNTY_PAID] = "Tu recompensa por [bounty_on] ha sido pagada por la cantidad de [amount] créditos."; 
$l_log_title[LOG_BOUNTY_PAID] = "Recompensa Pagada."; 
$l_log_text[LOG_BOUNTY_CANCELLED] = "Tu recompensa por [bounty_on] por la cantidad de [amount] créditos te ha sido devuelta."; 
$l_log_title[LOG_BOUNTY_CANCELLED] = "Recompensa Devuelta."; 
$l_log_text[LOG_SPACE_PLAGUE] = "Tu planeta [name] en el sector [sector] ha sido atacado por una Plaga Espacial. Un [percentage] por ciento de los colonos han muerto."; 
$l_log_title[LOG_SPACE_PLAGUE] = "¡Plaga Espacial!"; 
$l_log_text[LOG_PLASMA_STORM] = "Tu planeta [name] en el sector [sector] ha sido azotado por una Tormenta de Plasma. Se ha perdido toda la energía almacenada."; 
$l_log_title[LOG_PLASMA_STORM] = "¡Tormenta de Plasma!"; 
$l_log_text[LOG_BOUNTY_FEDBOUNTY] = "La Federación ha ofrecido una recompensa por tu cabeza por la cantidad de [amount] créditos."; 
$l_log_title[LOG_BOUNTY_FEDBOUNTY] = "¡Recompensa de la Federación!"; 
$l_new_pwis = "Tu contraseña es"; 
$l_planet2_sector = "No estás en el mismo sector que ese planeta."; 
$l_planet_destroyplanet = "Destruir Planeta"; 
$l_planet_warning = "Al hacer esto destruirás totalmente este planeta"; 
$l_planet_confirm = "¿Realmente quieres destruir este planeta?"; 
$l_port_bounty = "No puedes acceder a un puerto especial mientras tengas una recompensa ofrecida por la Federación.<br>"; 
$l_port_bounty2 = "Pulsa <a href=\"port.php?pay=1\">aquí</a> para pagar la recompensa de [amount] créditos."; 
$l_port_btynotenough = "No tienes suficientes créditos para pagar la recompensa de [amount] créditos.<br>"; 
$l_port_bountypaid = "Has pagado la recompensa. Pulsa <a href=\"port.php\">aquí</a> para continuar.<BR>";
$l_port_loannotrade = "IGB ha establecido un bloqueo en la cuenta de tu nave debido a un retraso en el pago de un préstamo. No puedes comerciar en un puerto especial hasta que devuelvas tu préstamo."; 
$l_team_notyours = "Debes estar en la Alianza para invitar a alguien."; 
$l_team_leavefirst = "Debes dejar un equipo primero antes de unirte a otro."; 


$l_tdr_engageagain = "Pulsa <A HREF=\"traderoute.php?engage=[tdr_engage]\">aquí</A> para hacer esta ruta comercial de nuevo, o aquí para hacerla <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=5\">cinco</A> o <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=10\">diez</A> o <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=50\">cincuenta</A> veces<p>";
$l_scan_bounty = "Esta nave tiene una recompensa total sobre ella de [amount] créditos."; 
$l_scan_fedbounty = "Esta nave tiene una recompensa sobre ella por parte de la Federación."; 
$l_by_nofedbounty = "Atacar a este jugador <b>NO</b> acabará con la Federación ofreciendo una recompensa por tu cabeza."; 

//Fig Drops

$l_sofa = "Ataque Sub-Orbital de Cazas"; 
$l_bombsaway = "Lanzas tus cazas bajando en espiral hacia el planeta mientras tú avanzas velozmente a máximo alcance."; 
$l_bigfigs = "Tu enorme nave les ha dado una amplia advertencia. Tus cazas serán menos efectivos."; 
$l_bigbeams = "Hay destellos brillates de lásers descargando. Tus cazas probablemente no consiguieron atravesar la atmósfera."; 
$l_bigtorps = "Una gran explosión aparece en la parte más alta de la atmósfera del planeta. Tus cazas probablemente no tuvieron tiempo de atacar."; 
$l_strafesuccess = "Parece que algunos de tus cazas han conseguido pasar, aunque no puedes decir cuántos son desde aquí."; 
$l_log_text[LOG_PLANET_BOMBED] = "Tu planeta [planet_name] en el sector [sector] ha sido bombardeado por [name]. Tú usaste [beams] energía y [torps] torpedos durante tu defensa.  Perdiste [figs] cazas."; 
$l_log_title[LOG_PLANET_BOMBED] = "<font color=red>¡Planeta bombardeado!</font>"; 
$l_lssd = "Última nave vista"; 
$l_lss = "Última nave vista en este sector"; 
$l_map = "Mapa"; 
$l_igb_errnobase = "IGB no puede transferir créditos a un planeta sin una base."; 
$l_planet_readlog_link = "Ver"; 
$l_planet_readlog = "[Ver] Diario del jugador"; 



//Changed messages

$l_log_text[LOG_TOW] = "Tu nave ha sido remolcada del sector [sector] al sector [sector] debido a que tu promedio de nivel tecnológico supera el valor límite de [hull]."; 



//Footer text
$l_footer_one_player_on = "Hay 1 jugador conectado."; 
$l_footer_players_on_1 = "Hay"; 
$l_footer_players_on_2 = "jugadores conectados"; 
$l_footer_until_update = "segundos hasta la nueva actualización."; 

//Ship officer insignia                
$l_insignia[0] = "Nuevo Recluta";      
$l_insignia[1] = "Tripulante";             
$l_insignia[2] = "Tripulante de Primera Clase"; 
$l_insignia[3] = "Suboficial de 3ª Clase"; 
$l_insignia[4] = "Suboficial de 2ª Clase"; 
$l_insignia[5] = "Suboficial de 1ª Clase"; 
$l_insignia[6] = "Suboficial en Jefe"; 
$l_insignia[7] = "Suboficial en Jefe Senior"; 
$l_insignia[8] = "Suboficial en Jefe Mayor"; 
$l_insignia[9] = "Alférez";           
$l_insignia[10] = "Teniente Grado Junior"; 
$l_insignia[11] = "Teniente";     
$l_insignia[12] = "Capitán de Corbeta"; 
$l_insignia[13] = "Comandante";          
$l_insignia[14] = "Capitán";                
$l_insignia[15] = "Capitán de Flota";  
$l_insignia[16] = "Comodoro"; 
$l_insignia[17] = "ContraAlmirante"; 
$l_insignia[18] = "ViceAlmirante"; 
$l_insignia[19] = "Almirante";            

// shipyard.php
$l_shipyard_title = "Astilleros";
$l_planet = "Planeta";

$l_cmb_needfighters = "Necesitas al menos 1 caza.";
// planet.php
$l_log_text[LOG_PLANET_YOUR_CAPTURED] = "Tu planeta [planet_name] en el sector [sector] fue derrotado y capturado por los malditos [name].";
$l_log_title[LOG_PLANET_YOUR_CAPTURED] = "<font color=red>Planeta capturado!</font>";


?>

